### ISSUE TITLE
Ctrl + Arrow word marking is only left-to-right, "Whatsie is already running"

### ISSUE THREAD

**Issue by adamkatav** [keshavbhatt/whatsie#10]
When writing rtl text using ctrl+arrow to jump between words the jumps are reversed, ctrl+left arrow skips to the right and ctrl+right skips to the left.

Also, a suggestion:
When opening the app, if it's already running than instead on an error message, the existing instance will be unminimized.

Thanks!

**Comment by keshavbhatt** [comment]
This is not whatsie's fault this how the underlying web view library called (QWebEngineView) is behaving, I have no control over it or i have made no changes to the behavior of RTL text in my implementation anywhere.

**Comment by keshavbhatt** [comment]
> When opening the app, if it's already running than instead on an error message, the existing instance will be unminimized.
#14 will add this feature.
