### ISSUE TITLE
Random segmentation faults

### ISSUE THREAD

**Issue by TheNetyx** [keshavbhatt/whatsie#101]
Whatsie randomly segmentation faults and gets killed. It always happens no matter what I do. Sometimes it happens in seconds, other times I can use it for hours before it segfaults and crashes.

version: 4.12
branch: master
commit: 147a4ff
built_at: 2023-02-02T06:16:12UTC

**Comment by keshavbhatt** [comment]
This is not reproducible in latest version of whatsie:

```
WhatSie
Version: 4.14
Source Branch: main
Commit Hash: 906ca7e
Build Datetime: 2023-05-20T15:56:15UTC
Qt Runtime Version: 5.15.4
Qt Compiled Version: 5.15.4
System: Ubuntu Core 20
Architecture: x86_64
Install mode: snap
```

**Comment by shakaran** [comment]
@TheNetyx, for random segfaults, the maintained fork **Whatly** disables GPU on Linux by default and adds crash recovery, on current Qt6. https://github.com/shakaran/whatly
