### ISSUE TITLE
Render Process Crash

### ISSUE THREAD

**Issue by teejavus** [keshavbhatt/whatsie#102]
Getting the following error - has happened about 6 times today. 

`Render process exited with code: 134
Do you want to reload the page ?`

![2023-02-10_14-53](https://user-images.githubusercontent.com/46339998/218054216-3c75612f-9dae-4cb0-818d-33d4c0c2c889.png)

**Debug Info:** 

Version: 4.10
Source Branch: main
Commit Hash: 74216cf
Build Datetime: 2023-01-23T07:40:13UTC
Qt Runtime Version: 5.15.8
Qt Compiled Version: 5.15.8
System: Arch Linux
Architecture: x86_64

(was installed using yay)

**Comment by keshavbhatt** [comment]
Not able to reproduce on:

```
WhatSie
Version: 4.14
Source Branch: main
Commit Hash: 906ca7e
Build Datetime: 2023-05-20T15:56:15UTC
Qt Runtime Version: 5.15.4
Qt Compiled Version: 5.15.4
System: Ubuntu Core 20
Architecture: x86_64
Install mode: snap
```

**Comment by shakaran** [comment]
@teejavus, the maintained fork **Whatly** adds self-healing crash recovery and, if the renderer keeps dying, stops looping and points at Settings → Performance instead. https://github.com/shakaran/whatly
