### ISSUE TITLE
Add video calling

### ISSUE THREAD

**Issue by douglas86** [keshavbhatt/whatsie#106]
Wouldn't it be awesome if you could make video calls through this app

**Comment by Yushi5058** [comment]
agree

**Comment by CRC-Mismatch** [comment]
Alas it would, but unfortunately, WhatsApp only implements this in their (proprietary) Desktop app (that's not available for Linux, at the very least)... Whatsie is recognized by WhatsApp as a "web" client, as if running under Chrome, and not as a full-fledged Desktop client... And it would probably touch on "sensitive spots" if this Whatsie started spoofing the official Desktop client, which would lead up to (para-)legal measures like "Cease & Desist" - that actually happened to a previous project which had the same name.

**Comment by shakaran** [comment]
@Yushi5058 @douglas86, video calling works in the maintained fork **Whatly**: WhatsApp Web's own voice and video calls run out of the box, and the call popout opens in its own window. https://github.com/shakaran/whatly
