### ISSUE TITLE
Downloading more than one image results in replacement

### ISSUE THREAD

**Issue by fesel2** [keshavbhatt/whatsie#110]
I tried to download more than one image from a chat and it turns out that WhatSie is trying to save each image with the same name, resulting in replacement of prior downloaded files.

**Comment by keshavbhatt** [comment]
I was not able to reproduce this behavior, but i will add something to prevent this in case it happen in rare cases.

**Comment by keshavbhatt** [comment]
This is fixed in dd687dc983614e133b841b6b942a13ff2dfd0ebf

**Comment by shakaran** [comment]
@fesel2, the maintained fork **Whatly** has a built-in download manager that tracks each download separately, so saving several images in a row is handled cleanly. https://github.com/shakaran/whatly
