### ISSUE TITLE
Not able to send messages with latest SNAP update on Ubuntu 22.04

### ISSUE THREAD

**Issue by MHBrand61** [keshavbhatt/whatsie#113]
I am using WHATSIE on Ubuntu 22.04. This morning (11.May.1023) I installed an available update of WHATSIE from the snap store. Since then I am not able to sent new messages. I can type new messages, but they are tagged with a clock and are not transferred.
However new messages are received.
I have also noticed, that QTWebEngineProcess if completely using one CPU core

**Comment by MichelHanzen** [comment]
Same problem with Linux Mint 21.1.

**Comment by keshavbhatt** [comment]
Will check. Thanks for reporting.

**Comment by keshavbhatt** [comment]
Please update to latest version of whatsie and report back if you still face the issue.

`snap refresh whatsie`

**Comment by MichelHanzen** [comment]
Whatsie updated to v4.13.0.c235b8a (Linux Mint 21.1). The problem is solved for me.
Thanks for your support!

**Comment by MHBrand61** [comment]
Also solved for me. Thanks a lot!

**Comment by claude27** [comment]
sorry, I still have this problem with Ubuntu 23.04, Whatssie 4.14.0.906ca7e :-(

Here is the debug info:
Version: 4.14
Source Branch: main
Commit Hash: 906ca7e
Build Datetime: 2023-05-20T15:56:15UTC
Qt Runtime Version: 5.15.4
Qt Compiled Version: 5.15.4
System: Ubuntu Core 20
Architecture: x86_64
Install mode: snap

**Comment by shakaran** [comment]
For sending broken on the snap, the maintained fork **Whatly** ships native packages (AppImage, .deb, .rpm) on current Qt6, which avoids the snap-specific breakage and tracks today's WhatsApp Web. https://github.com/shakaran/whatly

cc @MHBrand61 @MichelHanzen @claude27
