### ISSUE TITLE
"Read more" link at end of message freezes Whatsie making it eat all CPU time

### ISSUE THREAD

**Issue by heguzi** [keshavbhatt/whatsie#115]
How to repeat:
A long message can have been cut short having a "Read more" link at the end. If not clicking the link makes the strange behaviour begin, then click also "Message info".
At the latest this makes Whatsie freeze in eternal loop eating all the CPU time.
My environment: Ubuntu 22.04.2 LTS

**Comment by keshavbhatt** [comment]
Please update to latest version of whatsie and report back if you still face the issue. 

`snap refresh whatsie`

**Comment by heguzi** [comment]
> `snap refresh whatsie`

`whatsie v4.13.0.c235b8a from keshavbhatt (keshavnrj✪) refreshed`

But the "About" of my Whatsie says: `WhatsApp Web client for Linux Desktop` `Version: 4.14`

The problem still occurs.

**Comment by keshavbhatt** [comment]
Try un-installing with:

`snap remove --purge whatsie`

And installing again

`snap install whatsie`

**Comment by heguzi** [comment]
Re-installed.

Now I can't repeat the problem any more because **I can't any more find the "Message info"**, which seems to have been the cause for the problem.

**Comment by keshavbhatt** [comment]
Thanks for confirming.

**Comment by shakaran** [comment]
@heguzi, the maintained fork **Whatly** runs on current Qt6 WebEngine and tracks today's WhatsApp Web layout, so the old "Read more" freeze is unlikely to reproduce. Worth a try. https://github.com/shakaran/whatly
