### ISSUE TITLE
Pacstall package manager

### ISSUE THREAD

**Issue by Diegiwg** [keshavbhatt/whatsie#123]
[Pacstall](https://github.com/pacstall/pacstall) is a community-driven AUR-like package manager for Ubuntu. We have an ongoing pull request to add [whatsie-git](https://github.com/pacstall/pacstall-programs/pull/3743) and [whatsie](https://github.com/pacstall/pacstall-programs/pull/3750) to our repository.

We have a few questions for you:
* Would you like to maintain the pacscript (similar to a PKGBUILD) yourself? We can maintain it for you if you decide not to.
* Could you include a section in your documentation showing Pacstall as a valid method of installation for whatsie for Debian/Ubuntu users? We could make a pull request for that if you want.

**Comment by keshavbhatt** [comment]
Thank you for showing interest in the project.

> * Would you like to maintain the pacscript (similar to a PKGBUILD) yourself? We can maintain it for you if you decide not to.

For now, I would like you to maintain it.

> * Could you include a section in your documentation showing Pacstall as a valid method of installation for whatsie for Debian/Ubuntu users? We could make a pull request for that if you want.

Sure thing, Once the PRs are merged you can open a PR here to add the instrcutions and availability of whatsie with pacstall, Or let me know what I have to add.

**Comment by keshavbhatt** [comment]
This was completed with https://github.com/pacstall/pacstall-programs/pull/3750

**Comment by shakaran** [comment]
@Diegiwg, the maintained fork **Whatly** ships AppImage, .deb, .rpm, Snap and AUR packages, so there are native install paths without Pacstall. https://github.com/shakaran/whatly
