### ISSUE TITLE
Not able to send messages on Ubuntu 23.04, after reboot old messages are remarked as unread

### ISSUE THREAD

**Issue by claude27** [keshavbhatt/whatsie#126]
I'm  not able to send messages on Ubuntu 23.04, after reboot old messages are remarked as unread even if they have already been read on the mobile phone.

Ubuntu 23.04, Whatssie 4.14.0.906ca7e

Here is the debug info:
Version: 4.14
Source Branch: main
Commit Hash: 906ca7e
Build Datetime: 2023-05-20T15:56:15UTC
Qt Runtime Version: 5.15.4
Qt Compiled Version: 5.15.4
System: Ubuntu Core 20
Architecture: x86_64
Install mode: snap

**Comment by KottV** [comment]
I though that qtwebengine on my system has gone broken.
But looks like it's a more common problem.

**Comment by MarcelloDM** [comment]
Hi to everyone, I quote @proofy. Needs to update API. WhatSie is not correctly working. 

Thank you.

**Comment by keshavbhatt** [comment]
For now the solution is to force logout by cleaning the persistent data from settings.

**Comment by dynamicpete** [comment]
Hi all,
I have the same problem. Cleaning the persistent data helps only for a short time.

Thanks!

**Comment by vmajor** [comment]
I think I got hit by the same issue. Cannot send messages, and can only receive them on startup or by forcing 'reload'. Nothing fixes the inability to send messages. This started two days go for me.

**Comment by iuridiniz** [comment]
> Hi all, I have the same problem. Cleaning the persistent data helps only for a short time.
> 
> Thanks!

Yes, I cleanup persistent data, but he problem occurs again.
same issue that https://github.com/keshavbhatt/whatsie/issues/145

**Comment by proofy** [comment]
Because of the issue, I used the webapp now. But after some weeks, I started WhatSie and it works without cleaning up, but also only for some days

**Comment by major-mayer** [comment]
Issue still exists. I cleared the data, but just a few days later the issue happened again.
This makes WhatSie pretty much unusable for me.

**Comment by keshavbhatt** [comment]
Please verify this with new version 4.15 of Whatsie released today and re-open the ticket again if the problem still persists.
Thanks

**Comment by shakaran** [comment]
@claude27, for sending breaking after a reboot, the maintained fork **Whatly** tracks current WhatsApp Web on an up-to-date Qt6 WebEngine, which fixed this class of send failures for many people. https://github.com/shakaran/whatly
