### ISSUE TITLE
Hide tray icon

### ISSUE THREAD

**Issue by mendez8** [keshavbhatt/whatsie#127]
Please provide a setting so I can disable the tray icon even when I want to keep Whatsie open.

**Comment by lightproof** [comment]
@mendez8 as a temporary workaround, you can try hiding/disabling the tray icon in your DE settings[^1] and turning off the `Minimize in tray in start` option in whatsie.
[^1]: KDE has this option, don't know about other DE's though

**Comment by mendez8** [comment]
Thanks @lightproof! please feel free to resolve this issue

**Comment by shakaran** [comment]
For hiding the tray icon, the maintained fork **Whatly** has a "hide tray icon" option in Settings, and it keeps a taskbar route back to the window so you are never stranded. https://github.com/shakaran/whatly

cc @mendez8 @lightproof
