### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by sebelk** [keshavbhatt/whatsie#130]
Hi,

On Fedora 38, I cannot build:

```
qmake
Project MESSAGE: This is a release build
Project MESSAGE: Installation prefix: /usr
Project ERROR: Unknown module(s) in QT: webengine
```

I have installed:

qt6-qtwebengine-6.5.2-1.fc38.x86_64
qt6-qtwebengine-devtools-6.5.2-1.fc38.x86_64
qt6-qtwebengine-devel-6.5.2-1.fc38.x86_64
qt5-qtwebengine-5.15.12-6.fc38.x86_64
qt5-qtwebengine-devtools-5.15.12-6.fc38.x86_64
qt5-qtwebengine-devel-5.15.12-6.fc38.x86_64
qt5-qtwebengine-freeworld-5.15.12-4.fc38.x86_64

qmake version:

```
qmake --version
QMake version 3.1
Using Qt version 6.5.2 in /usr/lib64
```

Am I missing something?
Thanks

**Comment by keshavbhatt** [comment]
I never tried to build the project with Qt6. 

Taking quick look at documentation: the module which hold webengine related classes in the past has been splitted to multiple ones now. 

Most of the c++ classes has been moved to module called webenginecore

see: https://doc.qt.io/qt-6/qtwebengine-index.html

**Comment by sebelk** [comment]
Thanks, for the record, I've just built on F38 it with:

`qmake-qt5`

I hope that in the future project built with Qt6 too.

Cheers

**Comment by keshavbhatt** [comment]
Sure, it will be migrated to Qt 6 in future.

**Comment by shakaran** [comment]
@sebelk, the maintained fork **Whatly** moved to CMake and ships prebuilt packages (AppImage, .deb, .rpm, Snap, AUR), so you can skip building. https://github.com/shakaran/whatly
