### ISSUE TITLE
Bug: Unable to send or receive messages

### ISSUE THREAD

**Issue by mauroxhr** [keshavbhatt/whatsie#133]
After compiling and installing whatsie, the application does not allow sending or receiving messages.

Error:
![image](https://i.imgur.com/jYShe20.png)

**Comment by keshavbhatt** [comment]
Please try to clear session from settings and login again to fix this issue. 
duplicates #145

**Comment by shakaran** [comment]
@mauromartinezr, the maintained fork **Whatly** runs current Qt6 WebEngine tracking today's WhatsApp Web, which restored messaging for many who hit this. https://github.com/shakaran/whatly
