### ISSUE TITLE
CALLS and ADDING STATUS

### ISSUE THREAD

**Issue by jkavod** [keshavbhatt/whatsie#134]
Please kindly add Calls and videos so one do not have to miss calls or video calls, also add a status feature such that i can add status on whatsapp

**Comment by keshavbhatt** [comment]
Only whatsapp web developer can add these features. once they will add they will reflect on whatsie as well.

**Comment by shakaran** [comment]
@thisskavod, calls work in the maintained fork **Whatly** (WhatsApp Web voice and video, out of the box), and status updates are viewable too. https://github.com/shakaran/whatly
