### ISSUE TITLE
Info: Building under Debian testing KDE Plasma 5 

### ISSUE THREAD

**Issue by Sadi58** [keshavbhatt/whatsie#138]
I use a **Debian Testing** system with **KDE Plasma** DE.
The packages `libqt5webengine5 libqt5webengine-data libqt5webenginecore5 libqt5webenginewidgets5 libqt5positioning5 libqt5positioning5-plugins libqt5positioningquick5` were already installed.
So I started by installing the packages `libx11-dev libx11-xcb-dev qtwebengine5-dev` with all their dependencies.
As the command "qmake" was not available, I also installed the packages `qt5-qmake qt5-qmake-bin`.
After "qmake" returned "`Project ERROR: Cannot run compiler 'g++'`", I also installed `g++` with all dependencies.
Next the command "make" returned this error message:
```
/usr/lib/qt5/bin/qwebengine_convert_dict dictionaries/ca_ES.dic qtwebengine_dictionaries/ca_ES.bdic
make: /usr/lib/qt5/bin/qwebengine_convert_dict: No such file or directory
make: *** [Makefile:525: qtwebengine_dictionaries/ca_ES.bdic] Error 127
```
I realized that this meant it was alo necessary to install the package `qtwebengine5-dev-tools` after which **all went well**.
**Whatsie** works perfect, and looks like the best WhatsApp client for Linux so far.
Thank you.

**Comment by Sadi58** [comment]
I just wanted to share my experience of successfully building and installing Whatsie under Debian Testing with KDE Plasma.
The compiler error above was solved by installing `g++` with its dependencies.
I didn't need to install `build-essential` package, which is described as "Informational list of build-essential packages".

**Comment by aliquo93** [comment]
I have the same problem on Kubuntu 24.04

**Comment by shakaran** [comment]
The maintained fork **Whatly** moved to CMake and ships prebuilt packages (AppImage, .deb, .rpm, Snap, AUR), so building under Debian is optional now. https://github.com/shakaran/whatly

cc @aliquo93
