### ISSUE TITLE
Native notification doesn't automatically discard after viewing message

### ISSUE THREAD

**Issue by AxeldeWater** [keshavbhatt/whatsie#141]
Linux Mint 21.2 Cinnamon here. 

Native notifications will pile up in the tray, even after viewing the messages in the app. This will often result into 30 notifications inside the tray even though I've read all the messages.

**Comment by keshavbhatt** [comment]
This is not possible ATM.

**Comment by shakaran** [comment]
The maintained fork **Whatly** sends notifications through the XDG desktop portal, so their lifetime (including auto-dismiss) is handled by your desktop's own notification service. https://github.com/shakaran/whatly
