### ISSUE TITLE
Unread messages count in systray noification icon not working well 

### ISSUE THREAD

**Issue by Sadi58** [keshavbhatt/whatsie#143]
1. I usually see only "1" (or rarely "2") in the systray notification icon although there are more unread messages. It's very very rare that I can see any greater number.

2. Also, only those messages received when WhatSie is running are counted. So, if there are already a number of unread messages when WhatSie is launched, one cannot notice this if the app stars minimized, which is the usual case.

**Comment by keshavbhatt** [comment]
This was fixed already.

**Comment by shakaran** [comment]
The maintained fork **Whatly** shows the unread count right on the tray icon (summed across accounts), and dims it when disconnected. https://github.com/shakaran/whatly
