### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by wiryonolau** [keshavbhatt/whatsie#149]
Hi whatsie suddenly blank after first loading

Restarting and reinstall doesn't works
If I run from console I got this error
```
Qt: Session management error: Authentication Rejected, 
reason : None of the authentication protocols specified 
are supported and host-based authentication failed
```

Currently running using snap in debian 11
```
version: 4.14, branch: main, commit: 906ca7e, built_at: 2023-05-20T15:56:15UTC
```

I just notice the folder in /home/user/snap/whatsie has  ```.themes``` folder that link to ```/snap/whatsie/146/data-dir/themes``` folder, but both folder not exist
How do I further debug ?

```
WhatSie
Version: 4.14
Source Branch: main
Commit Hash: 906ca7e
Build Datetime: 2023-05-20T15:56:15UTC
Qt Runtime Version: 5.15.4
Qt Compiled Version: 5.15.4
System: Ubuntu Core 20
Architecture: x86_64
Install mode: snap
```

**Comment by dmitrii-maksimov** [comment]
Same problem since today

**Comment by jdvor** [comment]
Same with me. The app was running fine until few days ago.

Running from command line produces this messages, the app window is blank:

```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Qt: Session management error: Could not open network socket
propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.516\" (uid=1000 pid=47843 comm=\"/snap/whatsie/146/usr/bin/whatsie \" label=\"snap.whatsie.whatsie (enforce)\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=667 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.516\" (uid=1000 pid=47843 comm=\"/snap/whatsie/146/usr/bin/whatsie \" label=\"snap.whatsie.whatsie (enforce)\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=667 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
"Object path cannot be empty"
```

**build info:**
version: 4.14, branch: main, commit: 906ca7e, built_at: 2023-05-20T15:56:15UTC

**host:**
Ubuntu 22.04.3 LTS
kernel: 6.2.0-37-generic
Gnome version: 42.9
Windowing system: Wayland

**Comment by jdvor** [comment]
> i went to settings and disabled the "full width view" then it worked again settings can be accessed from the tray icon i dont know if this is related to the underlying issue or just a lucky coincidence

It fixed it on my end as well, so probably not just a coincidence.

**Comment by acalanato** [comment]
> i went to settings and disabled the "full width view" then it worked again settings can be accessed from the tray icon i dont know if this is related to the underlying issue or just a lucky coincidence

Same problem, different console log, same solution.

v4.14.0.906ca7e
Installed via snapd on Debian 12

**Comment by diederikvanbochove** [comment]
Same problem, same workaround. However with " full with view" WhatSie doesn't look nice. It works, it keeps my using WhatSie, but a fix would be nice.


Version: 4.14
Source Branch: HEAD
Commit Hash: 906ca7e
Build Datetime: 2023-05-21T02:57:13UTC
Qt Runtime Version: 5.15.10
Qt Compiled Version: 5.15.9
System: KDE Flatpak runtime
Architecture: x86_64
Install mode: flatpak

Fedora KDE 38
Wayland

**Comment by AxeldeWater** [comment]
Same problem here, same solution worked for me. Should be rapidly fixed though. 

I am not noticing the difference between full width view turned on and off, what was the difference?

**Comment by keshavbhatt** [comment]
WhatsApp web has changes changed something on thier side. we need to align with the changes. i will look into it today. thanks for reporting.

**Comment by shakaran** [comment]
For the blank-screen / white-window class of bug on some GPU/driver/Wayland setups: the maintained MIT fork **Whatly** disables GPU acceleration on Linux by default (the usual cause) and adds self-healing start-up crash recovery that escalates to safer rendering flags automatically, plus manual GPU toggles in Settings → Performance. https://github.com/shakaran/whatly

cc @wiryonolau @AxeldeWater @acalanato @clotodex @diederikvanbochove @dmitrii-maksimov @jdvor
