### ISSUE TITLE
Spell checker doesn't show languages

### ISSUE THREAD

**Issue by Sadi58** [keshavbhatt/whatsie#156]
This is something I've overlooked until now. After building and installing the Settings window is displayed with no languages to select for spell checker although I can see the dictionary files in "/usr/share/org.keshavnrj.ubuntu/WhatSie/qtwebengine_dictionaries".

Debian Testing
KDE Plasma Version: 5.27.9
KDE Frameworks Version: 5.107.0
Qt Version: 5.15.10

**Comment by MichelHanzen** [comment]
Same problem with Whatsie 4.15 on Ubuntu 24.04 (Qt version 6.4.2)

**Comment by Sadi58** [comment]
I no longer have this: I might have fixed it. 😉
Before building Whatsie, I went into "./src/dictionaries/" and (1) copied "tr_TR.aff" and "tr_TR.dic" from the directory "/usr/share/hunspell/" in my system, and then (2) removed all the dictionary files that I'll never use - other than English.
I can now see "en_GB" and "tr_TR" listed, but somehow not "en_US", probably those dictionary files are not good enough.
I'll try using both "en_GB" and "en_US" files from "/usr/share/hunspell/" next time I build.

**Comment by shakaran** [comment]
For the spell checker not listing languages, the maintained fork **Whatly** bundles the dictionaries and shows a working language picker in Settings. https://github.com/shakaran/whatly

cc @Sadi58 @MichelHanzen
