### ISSUE TITLE
Hide sidebar when window is narrow

### ISSUE THREAD

**Issue by antrmn** [keshavbhatt/whatsie#159]
A long time ago I used Stylus + a custom CSS picked somewhere in the Internet to achieve responsiveness on the Whatsapp web page: when the page has been shrunk, the sidebar collapses. 

Unfortunately, I can't find that custom CSS anywhere anymore. However, it would be great to have something similar on Whatsie.

**Comment by keshavbhatt** [comment]
Sorry but at the moment I am resisting myself from adding anything custom to the whatsapp web page. The reason is the upstream keeps changing the page and it becomes hard to maintain and keep up with those changes.

**Comment by shakaran** [comment]
@antrmn, the maintained fork **Whatly** can collapse the chat list to a strip of profile pictures (a button in WhatsApp's sidebar), giving the width back to the conversation. It's manual rather than width-triggered, but it covers the same need. https://github.com/shakaran/whatly
