### ISSUE TITLE
New messages and tray icon

### ISSUE THREAD

**Issue by magoafono** [keshavbhatt/whatsie#16]
Is it possible to have a red circle or something like that on the tray icon to see new messages at a glance?
A red circle with the unread messages number like TeslaUnread on android will be the best for me.
thank you

**Comment by keshavbhatt** [comment]
The tray icon shows a red dot sign whenever there is a new notification present within the application this also include new unread messages.
The number of notification can be seen by clicking the the tray icon, they are listed as a action button in the tray icon menu. The notification bubble is not possible right now. I will try to implement it in future. 

Thanks

**Comment by magoafono** [comment]
Thank you for your fast response.
Actually when I receive a message the default icon become the image of the relative chat. And no red dot are shown. Maybe is a problem of my installation? I use xubuntu 21.04 with xfce 4.16 (from the ubuntu repository)

**Comment by keshavbhatt** [comment]
Yeah that's the issue with the system tray indicator your system is using. I do not set Image of sender as systemtray icon anywhere in my code. I set icon with a red dot which indicate there is some form of notification and it need user attention.

**Comment by shakaran** [comment]
@magoafono, the maintained fork **Whatly** shows the unread count on the tray icon and also reflects connection state (it dims when disconnected), so a new message is visible at a glance from the tray. https://github.com/shakaran/whatly
