### ISSUE TITLE
Excessive CPU usage

### ISSUE THREAD

**Issue by serchist** [keshavbhatt/whatsie#163]
![image](https://github.com/keshavbhatt/whatsie/assets/38683060/fde0266d-a006-4726-9bc6-06949c3d5306)
Top CPU user in system, more than one xeon ht core.

**Comment by MichelHanzen** [comment]
Same problem with version 4.14 on AMD Ryzen 7. The application is burning one thread and it's not possible anymore to send messages.

**Comment by MichelHanzen** [comment]
I tried several times without success. I also tried to uninstall/install (flatpak).
I attached my system config to this post
[system config.txt](https://github.com/keshavbhatt/whatsie/files/14896021/system.config.txt)

**Comment by MichelHanzen** [comment]
Solved by uninstalling/reinstalling WhatsApp on my Android phone.

**Comment by keshavbhatt** [comment]
There must be some improvements with the latest release of Whatsie. Please verify if this problem still exists in new version 4.15 of Whatsie released today and re-open the ticket again if the problem still persists.
Thanks

**Comment by shakaran** [comment]
For high CPU, the maintained fork **Whatly** disables GPU acceleration on Linux by default and exposes compositing and process-model switches in Settings > Performance to bring it down. https://github.com/shakaran/whatly

cc @serchist @MichelHanzen
