### ISSUE TITLE
Only Fullscreen

### ISSUE THREAD

**Issue by TFrank12** [keshavbhatt/whatsie#164]
I can only use Fullscreen and this disturb me. Is there any Option to Change it to window Mode. I use Debian Testing x64

**Comment by keshavbhatt** [comment]
What happen when you press F11?

**Comment by keshavbhatt** [comment]
Please verify this with new version 4.15 of Whatsie released today and re-open the ticket again if the problem still persists.
Thanks

**Comment by shakaran** [comment]
@TFrank12, the maintained fork **Whatly** has a Fullscreen toggle (tray and command-palette action, plus a shortcut), so you are not stuck in it. https://github.com/shakaran/whatly
