### ISSUE TITLE
Segfault leads to complete system freeze

### ISSUE THREAD

**Issue by dochdoch** [keshavbhatt/whatsie#167]
If I leave whatsie running in the system tray it will eventually freeze the entire system, requiring a reboot.

Dmesg shows:
[65075.618103] whatsie[152226]: segfault at b1 ip 00000000000000b1 sp 00007fff26a05438 error 14 likely on CPU 5 (core 2, socket 0)

Linux Mint 21.3
Kernel 6.5.0-26-generic
DE: Cinnamon 6.0.4
WM: Mutter (Muffin)
CPU: AMD Ryzen 7 5700U with Radeon Graphics (16) @ 4.372GHz
GPU: AMD ATI 04:00.0 Lucienne
Memory: 7258MiB / 19807MiB

**Comment by keshavbhatt** [comment]
Please verify this with new version 4.15 of Whatsie released today and re-open the ticket again if the problem still persists.
Thanks

**Comment by shakaran** [comment]
@dochdoch, for a start-up segfault, the maintained fork **Whatly** adds self-healing crash recovery (safer rendering after a crash) plus an optional auto-restart, on current Qt6. https://github.com/shakaran/whatly

**Comment by dochdoch** [comment]
Hey thanks for the info, I do appreciate the support, but I simply moved away from whatsapp entirely.
