### ISSUE TITLE
Unable to exit fullscreen mode

### ISSUE THREAD

**Issue by psy-therapist** [keshavbhatt/whatsie#169]
Unable to exit fullscreen mode on ubuntu after watching video fullscreen.

**Comment by keshavbhatt** [comment]
pressing shortcut key F11 toggles the fullscreen view in application.

**Comment by keshavbhatt** [comment]
This will be fixed in next release.

**Comment by shakaran** [comment]
@psy-therapist, the maintained fork **Whatly** has a proper Fullscreen toggle (a tray and command-palette action, plus a shortcut), so you can leave fullscreen cleanly. https://github.com/shakaran/whatly
