### ISSUE TITLE
Stuck on "Loading your messages"

### ISSUE THREAD

**Issue by firubat** [keshavbhatt/whatsie#170]
Every once in a while Whatsie gets stuck on the "Loading your messages" screen, after it seemed it has finished loading (showing 100% or full progress bar). Restarting the app doesn't help, I have to unlink and relink (sometimes even that doesn't work on the first go).

I use linux Mint 21.2, whatsie version 4.14.2 as flatpak.

Edit: as I wrote this I realized last time it happened it might have been after installing some flatpak updates, but not exactly sure. I'll try to pay more attention to this.

**Comment by mbluett88** [comment]
I am experiencing the exact same situation with Whatsie 4.14.2 when running on Linux Mint 12.3 with Cinnamon.

**Comment by AndreGorny** [comment]
I'm having the same issue here.
I've already removed (--purge) the app, reinstall and relink, and still the same problem.

Any sugestions?

**Comment by AndreGorny** [comment]
I've tried to open it via terminal and recieved the following message:

/$ whatsie
Gtk-Message: 17:17:19.122: Failed to load module "xapp-gtk3-module"
Qt: Session management error: Could not open network socket
propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.143\" (uid=1000 pid=9082 comm=\"/snap/whatsie/148/usr/bin/whatsie \" label=\"snap.whatsie.whatsie (enforce)\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=768 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.143\" (uid=1000 pid=9082 comm=\"/snap/whatsie/148/usr/bin/whatsie \" label=\"snap.whatsie.whatsie (enforce)\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=768 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
"Object path cannot be empty"/$ whatsie
Gtk-Message: 17:17:19.122: Failed to load module "xapp-gtk3-module"
Qt: Session management error: Could not open network socket
propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.143\" (uid=1000 pid=9082 comm=\"/snap/whatsie/148/usr/bin/whatsie \" label=\"snap.whatsie.whatsie (enforce)\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=768 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.143\" (uid=1000 pid=9082 comm=\"/snap/whatsie/148/usr/bin/whatsie \" label=\"snap.whatsie.whatsie (enforce)\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=768 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
"Object path cannot be empty"

Could it be the problem? If it is, any idieas about how to fix it?

**Comment by evdbovenkamp** [comment]
I have the same problem on Ubuntu 23.10 (snap)

**Comment by keshavbhatt** [comment]
Please verify and reopen this ticket if this still happens in new version 4.15 of Whatsie.

**Comment by AshkanArabim** [comment]
I have the same issue on my AUR install (version 4.16.0-1)
I haven't checked snap yet.

![image](https://github.com/user-attachments/assets/75ce3a7c-f6f7-4447-aa9e-ae934a4424ff)

**Comment by Novack** [comment]
Having the very same problem in both AUR and Flatpack installs on Manjaro.

**Comment by shakaran** [comment]
For the stuck-on-loading state: the maintained fork **Whatly** is on current Qt6 WebEngine and exposes cache controls + a storage view in settings, so clearing the cached data (a common fix for this) is a couple of clicks. Worth a try if it still hangs. https://github.com/shakaran/whatly

cc @firubat @AndreGorny @AshkanArabim @Novack @evdbovenkamp @mbluett88 @prury
