### ISSUE TITLE
URL Handler Integration

### ISSUE THREAD

**Issue by geferdiansyah** [keshavbhatt/whatsie#172]
I don’t know where the issue lies, but I feel that WhatSie doesn’t automatically open a new chat when I click link or access it through the browser using api.whatsapp.com. 

What should I do so that WhatSie can open a chat when I access api.whatsapp.com/send/?phone=6xxxx or wa.me/xxxx, to make it easier for me to chat with several people using a custom text that I have set up in a spreadsheet. Thank you.

**Comment by code2be** [comment]
OK, Just tested [https://api.whatsapp.com/send/?phone=********](https://api.whatsapp.com/send/?phone=********) using Firefox, and opened in *whatsie* smoothly.

**Comment by keshavbhatt** [comment]
Cannot reproduce

**Comment by shakaran** [comment]
The maintained fork **Whatly** has a "New chat / open URL" command (and `whatly --send`) to open a chat from a link or number. https://github.com/shakaran/whatly

cc @code2be @geferdiansyah
