### ISSUE TITLE
WhatSie keeps shutting down

### ISSUE THREAD

**Issue by RagnarBelial** [keshavbhatt/whatsie#174]
I am running the latest version
WhatSie
Version: 4.15
Source Branch: HEAD
Commit Hash: e030486
Build Datetime: Sat May 25 18:44:25 2024
Qt Runtime Version: 5.15.10
Qt Compiled Version: 5.15.10
System: KDE Flatpak runtime
Architecture: x86_64
Install mode: flatpak

on Linux Mint and it's shutting down by itself about every 10-20 minutes. 
Any idea?

**Comment by keshavbhatt** [comment]
I didn't tested yet the flatpak build. I will try it today myself.

**Comment by RagnarBelial** [comment]
This happened

Gtk-Message: 08:01:42.676: Failed to load module "xapp-gtk3-module"
Qt: Session management error: Could not open network socket

<--- Last few GCs --->

[2:0x18a00000000]   657456 ms: Mark-sweep 1985.8 (2067.8) -> 1980.7 (2069.0) MB, 3996.7 / 0.2 ms  (average mu = 0.414, current mu = 0.200) task scavenge might not succeed
[2:0x18a00000000]   661919 ms: Mark-sweep 1987.9 (2069.0) -> 1982.9 (2071.3) MB, 3636.2 / 0.3 ms  (average mu = 0.313, current mu = 0.185) task scavenge might not succeed


<--- JS stacktrace --->


[1]+  Exit 134                ./com.ktechpit.whatsie

**Comment by RagnarBelial** [comment]
Some more digging in the logs
syslog:May 26 06:52:11 Drakkar systemd[1309]: Started app-flatpak-com.ktechpit.whatsie-30707.scope.
syslog:May 26 07:05:23 Drakkar systemd-coredump[32487]: Process 30720 (whatsie) of user 1000 dumped core.#012#012Stack trace of thread 34:#012#0  0x00007f1745b7fe14 n/a (n/a + 0x0)
syslog:May 26 07:05:24 Drakkar systemd[1309]: app-flatpak-com.ktechpit.whatsie-30707.scope: Consumed 19min 43.752s CPU time.
syslog:May 26 07:13:48 Drakkar systemd[1309]: Started app-flatpak-com.ktechpit.whatsie-32793.scope.
syslog:May 26 07:18:17 Drakkar systemd[1309]: Started app-flatpak-com.ktechpit.whatsie-34081.scope.
syslog:May 26 07:26:58 Drakkar systemd-coredump[34316]: Process 32805 (whatsie) of user 1000 dumped core.#012#012Stack trace of thread 34:#012#0  0x00007f242078ce14 n/a (n/a + 0x0)
syslog:May 26 07:26:59 Drakkar systemd[1309]: app-flatpak-com.ktechpit.whatsie-32793.scope: Consumed 19min 56.319s CPU time.
syslog:May 26 07:48:11 Drakkar systemd[1309]: Started app-flatpak-com.ktechpit.whatsie-35001.scope.
syslog:May 26 07:48:20 Drakkar systemd[1309]: Started app-flatpak-com.ktechpit.whatsie-35104.scope.
syslog:May 26 07:48:56 Drakkar systemd[1309]: Started app-flatpak-com.ktechpit.whatsie-35166.scope.
syslog:May 26 07:50:37 Drakkar systemd[1309]: Started app-flatpak-com.ktechpit.whatsie-35246.scope.
syslog:May 26 07:50:43 Drakkar kernel: [61677.710712] traps: whatsie[35012] general protection fault ip:7fc88345bf64 sp:7ffee1a52a60 error:0 in libQt5Core.so.5.15.10[7fc8831df000+328000]
syslog:May 26 07:50:50 Drakkar systemd-coredump[35279]: Process 35012 (whatsie) of user 1000 dumped core.#012#012Found module /app/bin/whatsie with build-id: 1ef9280e10d37eb8cc6fc72dcc36a7f768fb58dc#012Stack trace of thread 2:#012#0  0x00007fc88345bf64 n/a (n/a + 0x0)

**Comment by keshavbhatt** [comment]
Tested today the flatpak build of latest release. Unfortunately, I didn't encounter this problem. 

My environment:
Ubuntu 22.04 
Wayland
i5 CPU
Onboard Intel graphics

**Comment by shakaran** [comment]
@RagnarBelial — for random shutdowns/crashes, the maintained fork **Whatly** adds self-healing start-up crash recovery (it escalates to safer rendering flags automatically after a crash) plus an optional *auto-restart on crash*. If it kept dying on you, the fork should hold up better. https://github.com/shakaran/whatly
