### ISSUE TITLE
crash on Xubunt 21.04 (possibly after JetBrainz Mono font installed)

### ISSUE THREAD

**Issue by coolemza** [keshavbhatt/whatsie#18]
----------------------------------------------------------------------------------------------------------------------------------------------------------------
/home/leonid$ whatsie

(whatsie:16835): dbind-WARNING **: 17:43:08.565: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-jFrHcuAK6F: No such file or direct
ry
QApplication: invalid style override passed, ignoring it.
    Available styles: Windows, Fusion
Fontconfig warning: FcPattern object weight does not accept value [0 205)
Segmentation fault (core dumped)

**Comment by keshavbhatt** [comment]
try what suggested here: keshavbhatt/BingWall#16

**Comment by coolemza** [comment]
![image](https://user-images.githubusercontent.com/9666579/130665606-71e9d3da-9720-4666-94d8-3aac7d479621.png)

**Comment by keshavbhatt** [comment]
Can you try to reinstall the snap by completely purging it with `snap remove --purge whatsie` and `snap install whatsie` and provide the feedback? 
Thanks

**Comment by coolemza** [comment]
![image](https://user-images.githubusercontent.com/9666579/130803827-1cc80f6e-fb6b-467e-9e48-a542c9d3c45c.png)

**Comment by coolemza** [comment]
and it started to work after removing JetBrains Mono font from system

**Comment by coolemza** [comment]
no chance to fix it? )

**Comment by keshavbhatt** [comment]
You said it started working after removing that specific font?

**Comment by keshavbhatt** [comment]
try rm -rf ~/snap/whatsie and run the app again. 

also there is new update for the app with new runtime Qt5.15.2 to update that

snap refresh whatsie --edge

**Comment by shakaran** [comment]
@coolemza, for that start-up crash, the maintained fork **Whatly** adds self-healing crash recovery (safer rendering flags after a crash) and runs on current Qt6, which is far more robust on older setups. https://github.com/shakaran/whatly
