### ISSUE TITLE
How to disable notification preview?

### ISSUE THREAD

**Issue by avshyz-gs** [keshavbhatt/whatsie#180]
I've recently updated whatsie to the most recent version (4.15.0-1)
After this update, I couldn't find the option to disable the preview of the notification

Was that option removed?

![image](https://github.com/keshavbhatt/whatsie/assets/91832996/47bbec11-045e-4a1d-a933-d609f0567ed1)

**Comment by keshavbhatt** [comment]
I don't think there was any such feature in the settings. 
Whatsapp web's settings allows you to do that in notification settings actually. Uncheck the second option.

![image](https://github.com/user-attachments/assets/33e3bcba-9b65-4266-bc3a-fbdf76620b56)

**Comment by shakaran** [comment]
@avshyz-gs, the maintained fork **Whatly** has focus mode (hides chat-list names and message previews) and per-contact notification rules, to keep message content out of view. https://github.com/shakaran/whatly
