### ISSUE TITLE
Start minimized (request)

### ISSUE THREAD

**Issue by FherStk** [keshavbhatt/whatsie#19]
Hi there!

Could be possible to add an option (could be through command line) to start whatsie minimized?

Thanks a lot in advance,
Fher

**Comment by keshavbhatt** [comment]
will add settings for that. Thanks

**Comment by franco-ruggeri** [comment]
Hi! Are there any updates on this?

**Comment by keshavbhatt** [comment]
nkt yet, will do it soon

**Comment by rishuinfinity** [comment]
As a temporary way, here is a method that works

https://askubuntu.com/questions/663187/how-can-i-run-a-program-on-startup-minimized

**Comment by keshavbhatt** [comment]
I will implement it Qt side, we dont need to rely on workarounds. I will
provide solution as soon as i will get to my system.
Thanks

**Comment by keshavbhatt** [comment]
This feature is live now, update Whatsie: 
`snap refresh whatsie`

**Comment by shakaran** [comment]
This one is implemented in the maintained fork **Whatly**: Settings → Window has *start minimized* (and *minimise to tray on start*), so it can boot straight to the tray at login. https://github.com/shakaran/whatly

cc @FherStk @franco-ruggeri @rishuinfinity
