### ISSUE TITLE
Notification doesn't appear on Ubuntu 24.04 LTS when using the Native option

### ISSUE THREAD

**Issue by raulgrangeiro** [keshavbhatt/whatsie#198]
When I try to use the Native notification option the app doesn't show a notification on my screen, just on the system's notification bay, and when I use the Customized notification option it shows on my screen the notification, but doesn't show it stored on the system's notification bay.

I showed it on the video below.

[Notification problem with Whatsie on Ubuntu 24.04 LTS](https://youtu.be/o29oEAgoBUA)

Please, would it be possible to fix it? It's the best WhatsApp app on Linux, it would be awesome if this issue could be fixed.

This is the snap version running on Ubuntu 24.04.1 LTS using Gnome 46 and Wayland.

God bless you!

**Comment by HichTala** [comment]
Got the same issue unfortunately...

**Comment by athulkrishnama** [comment]
same issue in fedora 40

**Comment by raulgrangeiro** [comment]
Thanks fot taking time to fix this issue, friend. God bless you!

**Comment by shakaran** [comment]
For notifications not appearing on Ubuntu 24.04, the maintained fork **Whatly** sends them through the XDG desktop portal, so they show as native notifications (Wayland included), with per-contact rules on top. https://github.com/shakaran/whatly

cc @raulgrangeiro @HichTala @athulkrishnama
