### ISSUE TITLE
Native notifications don't work in Kubuntu 20.04.2

### ISSUE THREAD

**Issue by andreale141** [keshavbhatt/whatsie#2]
First thank you for your work and dedication, today is the only WhatsApp client that is worth in the GNU/Linux ecosystem. 

In the settings section, when you select the native notifications option regardless of the time in seconds, the notification appears but in a fraction of a second and disappears immediately. 

Distribution: Kubuntu 20.04.2
KDE Plasma 5.18.5
KDE Frameworks 5.68.0
Qt: 5.12.8
Kernel: 5.8.0-50

Thank you very much and blessings on your work.

**Comment by keshavbhatt** [comment]
Hi, thanks for opening this up. 

I didn't got time to test the app on different Distros and desktop environments yet. So if you can provide a short clip or GIF animation to show what exactly happening would be great help. 

Glad you liked the app so far.

**Comment by andreale141** [comment]
Hi Keshav Bhatt, I am very grateful for your prompt response and attention. Sure, here is a sample:

![Peek 29-04-2021 17-10](https://user-images.githubusercontent.com/31290735/116626038-3f35e680-a910-11eb-8ba6-c414557b2bc1.gif)

And it happens the same when a real time message arrives. As you can realize the custom notification works great, but the native notification is not usable.

Thank you very much for taking some of your time.

**Comment by shakaran** [comment]
@andreale141, the maintained fork **Whatly** sends native notifications through the XDG desktop portal, so they work on KDE and Kubuntu (and Wayland), with per-contact notification rules on top. https://github.com/shakaran/whatly
