### ISSUE TITLE
Tray icon menu issue

### ISSUE THREAD

**Issue by kaktus07** [keshavbhatt/whatsie#20]
Hi
On Zorin OS Lite 15.3 a right click on the tray icon makes the menu appear only for 0.5 seconds and minimizes the app. A second right click maximizes the app.
However, if clicked on a workspace where the app isn't active, then it switches the screen to the workspace with Whatsie or sometimes the menu behaves as expected.
I believe, that a right click should always only show the menu, no matter on which workspace it is done.

**Comment by erayerdin** [comment]
Confirmed on KDE Neon 20.04.

**Comment by rcsm17** [comment]
Same thing on Ubuntu 20.04 with Gnome 41... Open the menu continuously seems temporarily fix the issue

**Comment by keshavbhatt** [comment]
This is fixed in version 4.0 

`snap refresh whatsie`

**Comment by shakaran** [comment]
For the tray-icon menu, the maintained fork **Whatly** reworked the tray menu (restore, view modes, add account, quit) and the icon reflects unread and connection state. https://github.com/shakaran/whatly

cc @kaktus07 @erayerdin @rcsm17
