### ISSUE TITLE
Chat Display Theme resets after every restart (Linux Mint)

### ISSUE THREAD

**Issue by dhu92** [keshavbhatt/whatsie#206]
Everytime I restart Whatsie, the theme is reset to the Light Theme - if I go into the options to change it, the theme is selected correctly (in this case Dark Theme), but it is not actually applied. To fix it I have to select a different option, save the change and then change to Dark Theme again, even though it was correctly selected in the menu. After the change, the theme works correctly, but needs to be readjusted every time.

I'm using Linux Mint 22, everything else seems to work correctly.

**Comment by dhu92** [comment]
that did it - maybe there should be a hint that there are different options available somewhere in the UI (probably when you're looking at the whatsapp settings)

**Comment by keshavbhatt** [comment]
Mostly Whatsie would show a system tray icon from where all the options can be accessed.

**Comment by shakaran** [comment]
@dhu92, for the chat theme resetting on restart, the maintained fork **Whatly** persists the theme choice across restarts and paints each view in the theme colour from launch, so it no longer reverts. https://github.com/shakaran/whatly
