### ISSUE TITLE
Ubuntu notifications

### ISSUE THREAD

**Issue by liulentdev** [keshavbhatt/whatsie#207]
Hi, after the newest update every time I receive a message, while whatsie is minimized and I'm doing something else on my pc, the app just closes itself

**Comment by keshavbhatt** [comment]
Which version of ubuntu are you using? 

You clicked the notification popup before th app crashed?

 Was it native notification or custom notification? 

Please try to run the app from terminal and provide logs. 

Thanks

**Comment by liulentdev** [comment]
Hi, thanks for reaching out so fast. 

So, my ubuntu version is Ubuntu 24.04.1 LTS

I don't even get a notification popup, it just closes the second i receive a message (if whatsie is not minimized and I'm in the app itself I can still send and receive normally).

This is ss from terminal: 
![Screenshot from 2024-10-28 00-19-26](https://github.com/user-attachments/assets/4029122c-cba4-4a47-800a-8cbd2449f093)

After I got a message and the app closed, this is what I got in terminal:
![Screenshot from 2024-10-28 00-26-11](https://github.com/user-attachments/assets/5981ef2a-68c2-4de6-b06d-f3638d6230ce)

(let me know if it's easier for you to copy paste you the log itself)

This bug started happening after the newest update, the app was working normally before.

**Comment by Cllux** [comment]
Confirming same issue, same build.  Linux Mint 22

**Comment by gedankenstuecke** [comment]
I had the same issue (Ubuntu 24.04), when using the custom notifications (which iirc were set as default). Switching to the native Gnome notifications solved the issue, in case people want a stopgap solution!

**Comment by liulentdev** [comment]
This actually work for me, thank you for the idea. Still it's just a band-aid solution and I hope the fix is coming. But, great catch, thanks again.

**Comment by gedankenstuecke** [comment]
Yeah, I also thought it would be useful to know for debugging!

**Comment by CommonLoon102** [comment]
> I had the same issue (Ubuntu 24.04), when using the custom notifications (which iirc were set as default). Switching to the native Gnome notifications solved the issue, in case people want a stopgap solution!

Sorry, where you do that exactly?
I'm having the same issue as the others here.

**Comment by gedankenstuecke** [comment]
You right click on the Whatsie logo in the menu bar on the top-right (at least for OOB Gnome under Ubuntu) and select _Settings_, which allows you to setup Whatsie itself.

**Comment by keshavbhatt** [comment]
The issue was caused due to Custom notification popup widget life-cycle. It is fixed in [dde6e02](https://github.com/keshavbhatt/whatsie/commit/dde6e024d097bf3fa36a08d2baa59c69f0bc0571)

**Comment by gedankenstuecke** [comment]
Thanks!

**Comment by shakaran** [comment]
On desktop notifications not showing on Ubuntu/GNOME: the maintained fork **Whatly** routes them through the XDG portal (works under Wayland and sandboxed setups) and adds per-contact notification rules. Worth a try if this still bites you. https://github.com/shakaran/whatly

cc @liulentdev @Cllux @CommonLoon102
