### ISSUE TITLE
portuguese accents

### ISSUE THREAD

**Issue by micaelverissimo** [keshavbhatt/whatsie#21]
Hi, I'm using the app in ubuntu 20 and I have problems writing Portuguese words that have accents like: módulo. This happens only inside of WhatSie, how can I solve this?

**Comment by voltaxvoltax** [comment]
Same problem here, Ubuntu 20.04 and accents don't work  for Portuguese chars ( á,à,ó,ò,é,ã,õ)
It only works if we copy-paste.
Can you please fix this issue?

**Comment by DarkWiller** [comment]
Hi, congratulations on your work. it's the best of all.

But I have a little problem.

Whatsie is not recognizing the accent in my Brazilian Portuguese language (ABNT 2).

Example: type "Idea"
But just write "Idea"

Can you check what's going on?

**Comment by vitormicillo** [comment]
Guys, Problems with accentuation are not solely app-dependant, remember that it also depends on the OS language pack and not just the web interface wrapping.

**Comment by micaelverissimo** [comment]
Hi @vitormicillo

I understand, but the problems appear only in the app, outside I can write perfectly: você, olá and so on. There is some configuration that I need to do in order to fix this?

**Comment by vitormicillo** [comment]
in the web browser the spell checker used is available in the browser itself, not the same as the operating system.
Eu falo um pouco de pt tambem amigo.

> Hi @vitormicillo
> 
> I understand, but the problems appear only in the app, outside I can write perfectly: você, olá and so on. There is some configuration that I need to do in order to fix this?

**Comment by manozzo** [comment]
I have the same problem too. In other WhatsApp 'apps' the portuguese accent it's OK. Works very well. The portuguese pt-BR ABNT2 keyboard configuration works very well in my entire Ubuntu. Could you provide us some solution?

Best Regards,

**Comment by yuuta-togashi** [comment]
I have the same problem

**Comment by fvroig** [comment]
Same problem here with Ubuntu 20.04. Accented characters work fine in all other applications except WhatSie. They also work fine in both Chrome and Firefox web browsers. So this seems to be a problem specific to the app. It's a pitty because WhatSie is probably the best whatsapp desktop application I ever tested. Please, provide a fix to this issue. Thanks

**Comment by murilosrg** [comment]
Same problem here...

**Comment by tsffra** [comment]
I have the same problem

**Comment by keshavbhatt** [comment]
Hi can any one you try, whatsie from edge channel and let me know if the problem is still there?

`snap refresh whatsie --edge`

**Comment by tsffra** [comment]
> Hi can any one you try, whatsie from edge channel and let me know if the problem is still there?
> 
> `snap refresh whatsie --edge`

Even after trying the solution above presents, the accent problem remains.

**Comment by keshavbhatt** [comment]
hi @tsffra can you try run whatsie with the following commands:

```
QT_IM_MODULE=xim whatsie
```

```
QT_IM_MODULE=ibus whatsie
```
on both check if accentuation is working correctly. 

thanks

**Comment by fvroig** [comment]
Unfortunately, none of the soluctions provided above solved the problem. Dead keys are not working as expected

**Comment by keshavbhatt** [comment]
Can you pass me the outpit of 
```im-config -a``` 
and 
```im-config -l```

**Comment by fvroig** [comment]
Hi. The output of the first command is in portuguese, I made a translation:

`im-config -a`
Current setting for input method:
  * Active configuration: ibus (fails normally)
  * Normal automatic choice: ibus (usually ibus or fcitx or uim)
  * Overlay rule:
  * Current overlay choice: (pt_BR)
  * Current automatic choice: ibus
  * Number of valid choices: 13 (usually 1)
The override rule is defined in /etc/default/im-config.
The configuration selected by im-config is activated by restarting X.
Explicit selection is not required to enable autoconfiguration, if active is default/auto/cjkv/missing
   Available input methods : ibus fcitx fcitx5 uim hime gcin maliit scim hangul thai xim kinput2 xsunpinyin
Unless you really need them all, please make sure to install only one input method tool.

`im-config -l`
 ibus xim

**Comment by keshavbhatt** [comment]
Hi @fvroig,

**Install whatsie from edge channel using**
`snap refresh whatsie --edge`

wait for the update to finish if there are any updates.

**run whatsie with the following command and check if it helps**:

`env QT_IM_MODULE=xim QT_XKB_CONFIG_ROOT=/snap/whatsie/current/qt515-core20/usr/share/X11/xkb QTCOMPOSE=/snap/whatsie/current/qt515-core20/usr/share/X11/locale snap run whatsie`

with the above command, we are setting IM to use `xim` backend plus setting some relevant environment.

**Comment by fvroig** [comment]
@keshavbhatt, I did the refresh, but neither directory /snap/whatsie/current/qt515-core20/usr/share/X11/xkb nor directory /snap/whatsie/current/qt515-core20/usr/share/X11/locale exist.

This is what I have:
```
ls /snap/whatsie/current/ -las
total 4
0 drwxr-xr-x 6 root root   61 fev 19 17:42 .
4 drwxr-xr-x 4 root root 4096 fev 20 11:23 ..
0 drwxr-xr-x 2 root root   37 fev 19 17:42 bin
0 drwxr-xr-x 3 root root   43 fev 19 17:42 meta
0 drwxr-xr-x 3 root root   79 fev 19 17:42 snap
0 drwxr-xr-x 4 root root   39 fev 19 17:41 usr
```
and 
```
ls /snap/whatsie/current/usr/share/ -las
total 0
0 drwxr-xr-x 3 root root 35 fev 19 17:41 .
0 drwxr-xr-x 4 root root 39 fev 19 17:41 ..
0 drwxr-xr-x 2 root root 38 fev 19 17:41 applications

```
and when running the command you suggest I got this:
```
env QT_IM_MODULE=xim QT_XKB_CONFIG_ROOT=/snap/whatsie/current/qt515-core20/usr/share/X11/xkb QTCOMPOSE=/snap/whatsie/current/qt515-core20/usr/share/X11/locale snap run whatsie
Gtk-Message: 16:57:39.425: Failed to load module "appmenu-gtk-module"
Gtk-Message: 16:57:39.484: Failed to load module "canberra-gtk-module"
Gtk-Message: 16:57:39.485: Failed to load module "canberra-gtk-module"
Qt: Session management error: Could not open network socket
Launching with argument ("/snap/whatsie/54/usr/bin/whatsie")
Test 1 Loaded correctly value: "web"
```
Initially, everything seem ok, but then when I press any dead key the following message appears

`qt.xkb.compose: failed to create compose table`

and dead keys still do not work

**Comment by keshavbhatt** [comment]
> but neither directory /snap/whatsie/current/qt515-core20/usr/share/X11/xkb nor directory /snap/whatsie/current/qt515-core20/usr/share/X11/locale exist.

Don't worry about the non-existing paths :) the content snap is virtually mounted at that location.

> and dead keys still do not work

<hr>

This is strange, I am also getting the `qt.xkb.compose: failed to create compose table` error but i can type using AltGr+key perfectly fine on both arch Linux and ubuntu 16.04

I just released revision 55 in the edge channel with a few modifications in it can you try again. Sorry in advance cause these things look System dependent, we are dealing with different input methods and their configurations.

try this way:
 - remove snap data-dir using
   `rm -rf ~/snap/whatsie`
 - update the content snap manually
   `snap refresh qt515-core20 --edge`
 - update whatsie
   `snap refresh whatsie --edge`

**Comment by tsffra** [comment]
II tried all the solutions mentioned, none of them worked.

**Comment by keshavbhatt** [comment]
@fvroig one more interesting find is:
when i try to run the app with `LANG="en_UK.UTF-8" whatsie` or `LANG="en_IN.UTF-8" whatsie`
then I don't get the `qt.xkb.compose: failed to create compose table` message in console, but when I run with 
`LANG="pt_BR.UTF-8" whatsie` I get the message. Also, I am able to type in both situations :smile:

**Comment by tsffra** [comment]
> @fvroig one more interesting find is: when i try to run the app with `LANG="en_UK.UTF-8" whatsie` or `LANG="en_IN.UTF-8" whatsie` then I don't get the `qt.xkb.compose: failed to create compose table` message in console, but when I run with `LANG="pt_BR.UTF-8" whatsie` I get the message. Also, I am able to type in both situations smile

This one works for me, LANG="en_IN.UTF-8". Problem Solving.

**Comment by keshavbhatt** [comment]
> This one works for me, LANG="en_IN.UTF-8". Problem Solving.
are you able to properly use dead keys in this way? :astonished:

**Comment by tsffra** [comment]
> > This one works for me, LANG="en_IN.UTF-8". Problem Solving.
> 
> are you able to properly use dead keys in this way? astonished

yes, exec in terminal > LANG="en_UK.UTF-8" whatsie, and portuguese accents worked for me.

![image](https://user-images.githubusercontent.com/71599599/154865415-6bd95b64-44a5-48ab-b9c6-23314a5974ac.png)

**Comment by keshavbhatt** [comment]
I will pass this environment variable from snapcraft file so you don't have to open whatsie like this. Thanks for confirming.

**Comment by keshavbhatt** [comment]
The issue is fixed in 0483b030043f13fe048f575882ffb78d4177b479
You can refresh whatsie with `snap refresh whatsie --stable` to get the changes.
Feel free to reopen for further assitance.

**Comment by fvroig** [comment]
Working fine here too. Thanks!

**Comment by murilosrg** [comment]
II tried all the solutions mentioned, none of them work for me.

**Comment by keshavbhatt** [comment]
I have made few more changes to environment, those who are still facing issues with ibus or fcitx input methods should check the latest updates and confirm if now everlasting works. make sure you have revision 64 installed on your system. The command to update is : `snap refresh whatsie`
Thank you.

**Comment by voltaxvoltax** [comment]
I've version 3.0 revision 65, still no Portuguese accents:
$ snap list |grep whats
whatsie                            3.0                         65     latest/stable    keshavnrj         -

**Comment by fvroig** [comment]
in my case, version 3.0 65 latest/stable is working fine, all portuguese dead keys work ok

**Comment by guilhermebellotti** [comment]
I'm on WhatSie 4.0 version and using Ubuntu 22.04 and no Portuguese accents 😕

**Comment by leodip** [comment]
Solved here. Here's what I did.

First make sure you have an .XCompose file in your home. Check this out: https://github.com/marcopaganini/gnome-cedilla-fix

Then quit all whatsie instances.

From your terminal:

```
snap run --shell whatsie

env|grep -e HOME
```

It will list something like:

`HOME=/home/leodip/snap/whatsie/136`

`exit`

`ln -s ~/.XCompose /home/leodip/snap/whatsie/136`

Open Whatsie and it should be working fine.

The instructions above will make Whatsie have access to ~/.XCompose.

**Comment by shakaran** [comment]
@micaelverissimo, the accents and dead-key problem was largely a Qt5 WebEngine input-method bug. The maintained fork **Whatly** runs on current Qt6 WebEngine, where dead-key/IME input behaves much better, so it's worth retrying if this blocked you. https://github.com/shakaran/whatly
