### ISSUE TITLE
[Ubuntu 24.04]  Whatsie crashes when process turns to  background

### ISSUE THREAD

**Issue by MarcelloDM** [keshavbhatt/whatsie#210]
### Description 
When Whatsapp is in use and it is turned to the background in processes context switch, the application crashes and the window is suddenly going closed 
The problem is related to the new latest version.

**Comment by jay-b2b** [comment]
I'm also having this problem on Ubuntu, i tried re-installing from the snap store

**Comment by gedankenstuecke** [comment]
This sounds like a duplicate of #207, which has potentially a temporary solution

**Comment by keshavbhatt** [comment]
The issue was caused due to Custom notification popup widget life-cycle. It is fixed in [dde6e02](https://github.com/keshavbhatt/whatsie/commit/dde6e024d097bf3fa36a08d2baa59c69f0bc0571)

**Comment by shakaran** [comment]
For crashing when it goes to the background, the maintained fork **Whatly** adds self-healing crash recovery and runs on current Qt6, which makes it far more robust here. https://github.com/shakaran/whatly

cc @jay-b2b

**Comment by gedankenstuecke** [comment]
Please stop spamming your fork @shakaran, by being that annoying with notifications I've already lost interest. /block

**Comment by shakaran** [comment]
> Please stop spamming your fork [@shakaran](https://github.com/shakaran), by being that annoying with notifications I've already lost interest. /block

A pity for you. I am just offering this for free and I only pretend reach more people (or old issuers). You always can silence notifications or unsubscribe for a topic or repo.

**Comment by gedankenstuecke** [comment]
Sure, for users reading this later on: Be aware that his "fork" is just AI slop and was rejected from Flathub for that reason :p

**Comment by shakaran** [comment]
> Sure, for users reading this later on: Be aware that his "fork" is just AI slop and was rejected from Flathub for that reason :p

Sure, for users reading this. You can keep 3 or 4 years issues without maintenance or replies and hoping that you get a fix or feature. But if you get notifications, you get annoyed.

And I can ensure you, that I use LLM, but I have the knowledge from 20 years writing code from my self and I check and review every line, so I am only leveraging a tool which allows me deploy more quickly and give RESULTS to people for FREE.

You cannot stop progress. Thank you.

**Comment by MarcelloDM** [comment]
@shakaran Stop being stupid. I let you thank the AI for your fork. We don't need to be fast and paying tokens to develope.

Goodbye.

**Comment by shakaran** [comment]
> [@shakaran](https://github.com/shakaran) Stop being stupid. I let you thank the AI for your fork. We don't need to be fast and paying tokens to develope.
> 
> Goodbye.

Thanks @MarcelloDM , with ZERO repositories and new account you are a BIG example to give me lessons to spend my own money in tokens for deliver improved software to other people. 

BTW, Two guys from Argentina annoyed with a Spanish guy. Unless this is not a world cup :)
