### ISSUE TITLE
WhatSie chrashes repeatedly after Fedora KDE upgrade from 40 to 41

### ISSUE THREAD

**Issue by Khorinius** [keshavbhatt/whatsie#211]
Repeated crashes, mainly after restarting the OS or when WhatSie is running in the background.

**Comment by gedankenstuecke** [comment]
This also sounds like a duplicate of #207, which has potentially a temporary solution

**Comment by keshavbhatt** [comment]
The issue was caused due to Custom notification popup widget life-cycle. It is fixed in [dde6e02](https://github.com/keshavbhatt/whatsie/commit/dde6e024d097bf3fa36a08d2baa59c69f0bc0571)

**Comment by shakaran** [comment]
For repeated crashes after a Fedora upgrade, the maintained fork **Whatly** bundles the NSS modules newer Fedora needs and adds self-healing crash recovery. https://github.com/shakaran/whatly

cc @Khorinius
