### ISSUE TITLE
Failed to load on Debian 11 - X11

### ISSUE THREAD

**Issue by jjopc** [keshavbhatt/whatsie#22]
Hi!
when I try to start the application I get the following result:
![image](https://user-images.githubusercontent.com/64495745/137633683-0ebb5401-1376-446e-904a-c269424f79e7.png)

I've installed the app from snap store.
Thank you very much!

**Comment by keshavbhatt** [comment]
I forted application to qt 5.15, try to update the application with
`snap refresh whatsie --stable` 
if it is not installed install with 
`snap install whatsie`
