### ISSUE TITLE
Checking 'Use Native File Dialog' causes File Dialog not to open in Ubuntu 21.10

### ISSUE THREAD

**Issue by RayneShall** [keshavbhatt/whatsie#23]
Running Ubuntu 21.10 on XOrg. When checking the option to `Use Native File Dialog` in Settings, File Dialog no longer opens when trying to attach files.

Steps to reproduce:
1) Check `Use Native File Dialog` in options
2) Try to attach a file to a chat.

Observed result:
- No File Dialog opens to allow selecting a file

Expected result:
- GNOME file dialog opens up, allowing selecting a file

Installed from: Snap

Debug info:
WhatSie
Version: 1.0
Build Date: Jul 24 2021
Build Time: 17:23:11
Qt Runtime Version: 5.13.0
Qt Compiled Version: 5.13.0
System: Ubuntu Core 18
Architecture: x86_64

Other notes:
- File Dialog opens ok when native option is unchecked, but (of course) it's not native
- Cannot try on Wayland, as it very much messes up a bit on my pc

**Comment by keshavbhatt** [comment]
Thanks for reporting, will try to replicate and file a fix.

**Comment by keshavbhatt** [comment]
This is fixed in 020ac6daeac226da90bc0c884a9b22a7da9baa99
Please update snap with:
`snap refresh whatsie --stable`

**Comment by shakaran** [comment]
@FedeAbella, the maintained fork **Whatly** keeps the "use native file dialog" option and is on current Qt6, where the native picker behaves correctly. https://github.com/shakaran/whatly
