### ISSUE TITLE
Theme keeps changing back to Light mode

### ISSUE THREAD

**Issue by mlchelCar** [keshavbhatt/whatsie#24]
Hi, I'm using Whasie on Ubuntu 20.04
Every time I restart the computer, the theme changes from dark to white mode.
That's a small problem, but really annoying.

**Comment by AnAlligatorPear** [comment]
Having same issue

**Comment by keshavbhatt** [comment]
Make sure you have the automatic theme switch disabled.

**Comment by shakaran** [comment]
For the theme reverting to light, the maintained fork **Whatly** persists the theme choice across restarts and can follow the system light/dark setting, so it stops flipping back. https://github.com/shakaran/whatly

cc @miskmichel @AnAlligatorPear
