### ISSUE TITLE
Whatsie started to crash on Fedora 35

### ISSUE THREAD

**Issue by glaydersonjonathan** [keshavbhatt/whatsie#25]
Greetings,

Suddenly, Whatsie started to crash everytime I tried to open it. I tried remove and install again through snap, delete ~/snap/whatsie/ directory and use the commands below, but had no sucess

```
sudo rm /var/cache/fontconfig/*
rm ~/.cache/fontconfig/*
fc-cache -r
```
The error I get on terminal is:

> Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
> Gtk-Message: 15:01:20.199: Failed to load module "canberra-gtk-module"
> Gtk-Message: 15:01:20.199: Failed to load module "pk-gtk-module"
> Gtk-Message: 15:01:20.200: Failed to load module "canberra-gtk-module"
> Gtk-Message: 15:01:20.200: Failed to load module "pk-gtk-module"
> QApplication: invalid style override passed, ignoring it.
>     Available styles: Windows, Fusion
> Fontconfig warning: FcPattern object weight does not accept value [0 205)
> Segmentation fault (core dumped)

![image](https://user-images.githubusercontent.com/17666104/150577898-b0d0fe64-cc05-45f2-a0c2-891d2ccf9e66.png)

I'm using Fedora 35. Anything I can do to get this working again? Thanks.

**Comment by dd4sk** [comment]
Hi,
i have exactly the same problem on Fedora 35. This happened after i did a dnf upgrade. On my Notebook, where i did not perform the updated yet whatsie still works.
Interesting thing is, that when i start it as root (with the no-sandbox option) the program is still starting.

**Comment by keshavbhatt** [comment]
Run this to remove the whatsie folder from your home directory
`rm -rf ~/snap/whatsie`
and try to run whatsie now.

The idea is to let wahtsie desktop-launch script regenreate the new fontconfig data and other stuff. which could be causing the issue.

**Comment by keshavbhatt** [comment]
`rm -rf ~/snap/whatsie`
and 
`snap refresh whatsie --stable`

**Comment by dd4sk** [comment]
Thanks. Its working again.

**Comment by keshavbhatt** [comment]
glad to hear :)

**Comment by shakaran** [comment]
For Fedora start-up crashes, the maintained fork **Whatly** added self-healing start-up crash recovery that escalates to safer rendering flags automatically after a crash. A Fedora start-up crash (on F44) was actually one of the issues that drove it, so it's worth trying if this still bites. https://github.com/shakaran/whatly

cc @glaydersonjonathan @dd4sk
