### ISSUE TITLE
Gnome Shell native desktop notification (request)

### ISSUE THREAD

**Issue by rcsm17** [keshavbhatt/whatsie#26]
In Gnome-Shell there is not an option to use the native desktop notification

**Comment by keshavbhatt** [comment]
Go to settings change the notitification type to native notification.

**Comment by rcsm17** [comment]
Hi @keshavbhatt, sorry for the late reply... 
Already done this but the result of enabling the native notification is that: 

![Screenshot from 2022-02-28 14-54-28](https://user-images.githubusercontent.com/44343476/155995319-cdbe5c0d-be2e-41f6-a2e3-0e446bfc7ace.png)

Consider that I'm running Gnome 41.1

**Comment by keshavbhatt** [comment]
What distribution you using?

**Comment by rcsm17** [comment]
I'm on Ubuntu 20.04 and I run Whatsie 3.0 installed from snap

**Comment by keshavbhatt** [comment]
I will ask my friend who has the same system to test, sorry for the inconvinience.

**Comment by rcsm17** [comment]
if it something that I can do I will be glad to help.. 
Thanks for your work !

**Comment by keshavbhatt** [comment]
Tested on Ubuntu 22.04 & everything works as expected.
also, try to update to the latest version of whatsie

`snap refresh whatsie`

**Comment by shakaran** [comment]
For native GNOME notifications, the maintained fork **Whatly** sends them through the XDG desktop portal, so they show up as proper native notifications under GNOME/Wayland (and in sandboxed setups), with per-contact notification rules on top. https://github.com/shakaran/whatly

cc @rcsm17
