### ISSUE TITLE
Unable to use enter for new line

### ISSUE THREAD

**Issue by DylanKirbs** [keshavbhatt/whatsie#28]
Enter automatically sends the message, and I can't seem to find a setting to change that. It would be much nicer to use Enter to move to a new line and Ctrl+Enter to send, like an email.

**Comment by keshavbhatt** [comment]
Shift+Enter makes the textbox go to the next line.  I don't see any issue with this behavior.

**Comment by DylanKirbs** [comment]
Would it not be possible to rebind the keys then?
