### ISSUE TITLE
How to change passwd after set one

### ISSUE THREAD

**Issue by tarcisiomiranda** [keshavbhatt/whatsie#29]
I've been using your program for a long time and I would like to know how I can change the program's password, once set I don't see an option to change it, just deactivate it.
Thx

**Comment by keshavbhatt** [comment]
This is not implemented yet, its in my todo list. Could come in future.

**Comment by shakaran** [comment]
@tarcisiomiranda, the maintained fork **Whatly** has an app lock whose passcode you can set and change from Settings. https://github.com/shakaran/whatly
