### ISSUE TITLE
How to open to chat new numbers?

### ISSUE THREAD

**Issue by altomarketing** [keshavbhatt/whatsie#3]
To send messeges for numbers i donbt have in agenda, In web browser i used to open https://web.whatsapp.com/send?phone=111111111  

 how can i open such links in this app ?

**Comment by keshavbhatt** [comment]
This is coming soon. Thanks

**Comment by keshavbhatt** [comment]
added in https://github.com/keshavbhatt/whatsie/commit/12f4214e6a3614bd787fc6027fb9025b15df34b1

**Comment by keshavbhatt** [comment]
Users can also access this feature with Ctrl+N, or from the system tray menu "New Chat".

**Comment by shakaran** [comment]
@altomarketing, the maintained fork **Whatly** can open a chat to a number that is not a contact: its "New chat / open URL" command, or `whatly --send` from the command line. https://github.com/shakaran/whatly
