### ISSUE TITLE
Feature Requests for Whatsie

### ISSUE THREAD

**Issue by rishuinfinity** [keshavbhatt/whatsie#30]
Hey, I really appreciate how wonderful app your whatsie is. But there are some features that I crave.I tried understanding the code but I currently dont know much about QT. Here are the requests:
* As whatsie is running in the background, it can be opened and closed by double clicking on the icon. Is there a command to reopen and close the window. Because I would like a shortcut for that(like Meta+ W to open and close whatsie window). If even there is a terminal command for doing so that currently exists, please relay the same.
* The current download method seems to be a little off, as it keeps on asking for a new folder each time I want to download a document. Could you add the download path in the settings only and download it directly to that Whatsapp Download Folder everytime without asking for the location. Or a soft fix would be to start downloading with the current selected folder without asking for a new folder everytime.
* Please add a time limit for auto locking whatsie, just like automatic fingerprint lock in Whatsapp Android app. Like after 1 minute it would lock automatically.
* Also, add an option to autolock it whenever it is minimized to tray

**Comment by keshavbhatt** [comment]
Thanks, I will add all these features in coming days.

**Comment by keshavbhatt** [comment]
> * The current download method seems to be a little off, as it keeps on asking for a new folder each time I want to download a document. Could you add the download path in the settings only and download it directly to that Whatsapp Download Folder everytime without asking for the location. Or a soft fix would be to start downloading with the current selected folder without asking for a new folder everytime.

This has been fixed in the latest v4.0


> * Please add a time limit for auto locking whatsie, just like automatic fingerprint lock in Whatsapp Android app. Like after 1 minute it would lock automatically.

This has been fixed in the latest v4.0

To update to whatsie 4.0 run 
`snap refresh whatsie`

Other features will land eventually, Thanks.

**Comment by rishuinfinity** [comment]
Cool, Really appreciate the good work. :1st_place_medal:

**Comment by rishuinfinity** [comment]
Hey, about the first enhancement I had requested, I propose a solution:
Currently When whatsie is run and
* if it has not been running then it runs normally.
* if its already running, it shows an alert window showing that it is already running.
Alternatively: What I propose is, when whatsie is run and it is already running, then it should raise the minimized whatsie window instead of showing the alert.

In this case, If I want to set a shortcut say "META + W"  to run whatsie, then i can easily set this shortcut in settings with the terminal command set as "whatsie".

**Comment by rishuinfinity** [comment]
I tried doing this myself, but I wasn't able to build the application after editing the code. Also, I would really like to contribute to this project, but I really dont know how to start. I'm not even sure if I should learn QT application, or rather I don't know whether its that mainstream as I find most apps in GTK. If you could, I'd really appreciate some guidance. Thanks.

**Comment by keshavbhatt** [comment]
Both Gtk and Qt contribute equally  in application  development  share on Linux. KDE and its application suite is completely based on Qt, while Gnome and its app suite uses GTK.

**Comment by keshavbhatt** [comment]
> Currently When whatsie is run and
> 
>     * if it has not been running then it runs normally.
> 
>     * if its already running, it shows an alert window showing that it is already running.
>       Alternatively: What I propose is, when whatsie is run and it is already running, then it should raise the minimized whatsie window instead of showing the alert.

already being tracked in these issues #38 #14 



> If I want to set a shortcut say "META + W" to run whatsie, then i can easily set this shortcut in settings with the terminal command set as "whatsie".

This one is provided by your Desktop Environment. I cannot implement anything like that in Application that can trigger its execution unless these is a helper process running in the background.(which most people will hate). I can register a global shortcut to trigger present/activate Whatsie window if it is already running though.

**Comment by shakaran** [comment]
@rishuinfinity — several requests in this thread are implemented in the maintained fork **Whatly**: multi-account with tabs, start-minimized, tray tweaks, custom CSS/JS, themes, spellcheck and messaging automation. Might be worth a look. https://github.com/shakaran/whatly
