### ISSUE TITLE
Feature Requests for Whatsie 

### ISSUE THREAD

**Issue by Codiecher** [keshavbhatt/whatsie#33]
1. Whenever I want to post an image, I can't just copy the image from another source and CTRL+V to send the image to a conversation.
2. Links don't embed automatically like they do on the mobile application, on the official web client, the link is embedded by clicking alt+enter after pasting a link in the message box, on whatsie neither works.

My other suggestions have been brought up by other users already, so I'll just keep them to myself.

Just wanted to say thanks for the client, it speeds up workflows :)

**Comment by keshavbhatt** [comment]
> 1. Whenever I want to post an image, I can't just copy the image from another source and CTRL+V to send the image to a conversation

Tested on the latest v4.0, it works.

> 2\. Links don't embed automatically like they do on the mobile application, on the official web client, the link is embedded by clicking alt+enter after pasting a link in the message box, on whatsie neither works.

Tested on the latest v4.0, it works.

You can run `snap refresh whatsie` to update to version 4.0

**Comment by shakaran** [comment]
@codiecher, many requests here are implemented in the maintained fork **Whatly**: scheduled messages, multi-account tabs, themes, spell-check, app lock, custom CSS/JS and messaging automation. https://github.com/shakaran/whatly
