### ISSUE TITLE
Every time I link my device it always auto-logout.

### ISSUE THREAD

**Issue by amrikarisma** [keshavbhatt/whatsie#36]
Every time I link my device it always auto-logout. On my device a message pops up and gives a link to : https://faq.whatsapp.com/general/seeing-devices-logged-out-unexpected-issue?lang=en

Please anyone can help me?

**Comment by amrikarisma** [comment]
` Gtk-Message: 20:30:37.447: Failed to load module "xapp-gtk3-module"
Gtk-Message: 20:30:37.748: Failed to load module "colorreload-gtk-module"
Gtk-Message: 20:30:37.748: Failed to load module "window-decorations-gtk-module"
js: Another connection wants to delete database 'wawc_db_enc'. Closing db now to resume the delete request.
js: Another connection wants to delete database 'wawc_db_enc'. Closing db now to resume the delete request.
js: Another connection wants to delete database 'model-storage'. Closing db now to resume the delete request.
js: Another connection wants to delete database 'fts-storage'. Closing db now to resume the delete request.
js: Dexie.delete('model-storage') was blocked
js: Another connection wants to delete database 'wawc'. Closing db now to resume the delete request.`

**Comment by keshavbhatt** [comment]
This is due to the recent switch of Whatsapp web, They are using the new version of Whatsapp now. I request you to update your application on your phone and clear the app cache and app data of Whatsie from settings. everything will work normally afterward.

**Comment by simonsaysthis** [comment]
Unfortunately its broken for me too. Don't have the problem with other third party apps.

**Comment by keshavbhatt** [comment]
I request you to logout from all sessions, clear Whatsie's application cache from settings, restart and Log back In.

**Comment by santiagodiaz1993** [comment]
I am experiencing the same issue. I logged out of everywhere (except my phone, the only way to "log out" I guess is to delete the app and re-install). I cleared the cache of Whatsie, and also tried uninstalling it and re-installing it. 

I had no luck.

**Comment by simonsaysthis** [comment]
> I had no luck. Any other suggestions?

Unfortunately it seems this Snap is borked. I switched to another app which works

**Comment by keshavbhatt** [comment]
> 
> > I had no luck. Any other suggestions?
> 
> Unfortunately it seems this Snap is borked. I switched to another app which works
> 

Sorry to hear that, but snap has nothing to do with this behavior.

**Comment by simonsaysthis** [comment]
Hi @keshavbhatt I am not saying snapd is the problem. Unfortunately its a bug with this particular app.

**Comment by omersi** [comment]
same here. 
it only disconnects from your app.

**Comment by keshavbhatt** [comment]
The issue is being tracked at #48 
hence closing it to avoid duplication.

**Comment by keshavbhatt** [comment]
The issue is being tracked at #48 
hence closing it to avoid duplication.

**Comment by shakaran** [comment]
For getting logged out and having to re-link every time, the maintained fork **Whatly** keeps a persistent per-account profile, so the session survives restarts and stays linked. https://github.com/shakaran/whatly

cc @amrikarisma @omersi @santiagodiaz1993 @simonsaysthis
