### ISSUE TITLE
At start, Whatsie seems to have a minimum width that I cannot control

### ISSUE THREAD

**Issue by SamuXzX** [keshavbhatt/whatsie#37]
Hi, thank you very much for your work. I've tried many wrappers for Whatsapp Web and this seems by far the best.
Here's my problem: every time I start Whatsie, it seems to have a minimum width it has to respect. So, even if the previous time I resized it (or even if all windows in my desktop environment have the same size), Whatsie is always a bit larger than it should.
Some examples:

This is how windows open in my DE:
![immagine](https://user-images.githubusercontent.com/30182251/164240841-f4cf030d-dc13-47c8-86bb-55e83c8bdb75.png)
They can automatically be resized by the compositor to occupy half of the screen.

This is how Whatsie opens:
I can't seem to understand why Whatsie always opens this way. I have to manually resize it every time.

---

If it is because at the actual zoom, which I can set in the settings of Whatsie, the site occupies more than half of the screen, why does it work this way even if I reduce the zoom in the settings?

**Comment by shakaran** [comment]
@SamuXzX, the maintained fork **Whatly** remembers your window layout (size and position) across launches, and can collapse the chat list to reclaim width. https://github.com/shakaran/whatly

**Comment by SamuXzX** [comment]
Are you posting on every Whatsapp wrapper repo? xD

**Comment by shakaran** [comment]
> Are you posting on every Whatsapp wrapper repo? xD

only on this for the moment, but not a bad idea post in others which are dead or unmaintained
