### ISSUE TITLE
"An Instance Of Whatsie Is Already Running"

### ISSUE THREAD

**Issue by SercanDmr** [keshavbhatt/whatsie#38]
Problem Scenario ->
---------------------
-Open application.
-Minimize application to system tray.
-Click application icon again(Not the tray one), you will get this warning.
---------------------
**Expected Behavior -> Just open the exist running instance, no need to warn the user about this.This change will affect user experience in very positive way.👍**

**Comment by keshavbhatt** [comment]
related to issue #14

**Comment by peter-sgp** [comment]
the same msg comes if I open a link from the web browser. e.g. https://wa.me/xxxxx
browser lets me to use Whatsie, but the app says "another instance is running" and it will not complete the request.
In order for the link to work, I need to kill whatsie and then click on the link in the browser again.

ps. running on Fedora 35

**Comment by keshavbhatt** [comment]
Yeah, I am aware of this issue. I will provide a solution soon.

**Comment by keshavbhatt** [comment]
Fixed in 8c0df6d34bba406e4d8e2711e4f5134a24107b2e

**Comment by SercanDmr** [comment]
> Fixed in [8c0df6d](https://github.com/keshavbhatt/whatsie/commit/8c0df6d34bba406e4d8e2711e4f5134a24107b2e)

After latest update when I click whatsie icon I got no warning but It's not restoring the exist session.

**Comment by keshavbhatt** [comment]
You should get a notification in your system tray if you set  native notification to channel your alerts. otherwise, you will get whatsie's own notification widget popped up on top right side of you screen.

**Comment by keshavbhatt** [comment]
I have not added implemented logic to directly raise the existing window. I think I should do that :D
Right now the user has to click on the notification popup in order to restore the window.

**Comment by SercanDmr** [comment]
> I have not added implemented logic to directly raise the existing window. I think I should do that :D Right now the user has to click on the notification popup in order to restore the window.

:D

**Comment by keshavbhatt** [comment]
> After latest update when I click whatsie icon I got no warning but It's not restoring the exist session.

This is fixed in 391171583a00d04b3f2fcfb57b9c9743ae286728
update whatsie with `snap refresh whatsie`

**Comment by shakaran** [comment]
If the single-instance lock is getting in your way, the maintained MIT fork **Whatly** supports named profiles (`--profile <name>`), so you can run several fully independent instances/accounts side by side — plus a built-in multi-account tabbed view. https://github.com/shakaran/whatly

cc @SercanDmr @peter-sgp
