### ISSUE TITLE
Whatsie consuming 7-10% CPU on idle, even if minimized to tray

### ISSUE THREAD

**Issue by belliriccardo** [keshavbhatt/whatsie#39]

**Comment by belliriccardo** [comment]
Sorry I opened the issue by mistake! It looks like it was some sort of setup/initialization process, I didn't think that it would last this long.

**Comment by shakaran** [comment]
@belliriccardo, for idle CPU, the maintained fork **Whatly** disables GPU on Linux by default and starts V8 in optimize-for-size mode, with more knobs in Settings → Performance. https://github.com/shakaran/whatly
