### ISSUE TITLE
Error when load app on Ubuntu

### ISSUE THREAD

**Issue by rodrigomessiasbarros** [keshavbhatt/whatsie#4]
Hello,

I'm installed whatsie on Ubuntu 20.04.02 - x86_64 by Gnome Software Snap and I have this error when load application:

```
rodrigo@nokk:~$ whatsie 

(whatsie:202138): Gtk-WARNING **: 23:07:05.823: Theme parsing error: gtk.css:1566:23: 'font-feature-settings' is not a valid property name
(whatsie:202138): Gtk-WARNING **: 23:07:05.826: Theme parsing error: gtk.css:3618:25: 'font-feature-settings' is not a valid property name
(whatsie:202138): Gtk-WARNING **: 23:07:05.826: Theme parsing error: gtk.css:4080:23: 'font-feature-settings' is not a valid property name
Gtk-Message: 23:07:05.862: Failed to load module "canberra-gtk-module"
Gtk-Message: 23:07:05.862: Failed to load module "canberra-gtk-module"
QApplication: invalid style override passed, ignoring it.
    Available styles: Windows, Fusion
Fontconfig warning: FcPattern object weight does not accept value [0 215)
Falha de segmentação (imagem do núcleo gravada)
```
![Captura de tela de 2021-05-07 23-13-42](https://user-images.githubusercontent.com/3493652/117522459-e9a1af80-af89-11eb-8f6b-5c66765c9efb.png)
![Captura de tela de 2021-05-07 23-14-44](https://user-images.githubusercontent.com/3493652/117522483-0a6a0500-af8a-11eb-9540-6ab784ec5c30.png)

If you need more log/information let me know.

Thanks,

Rodrigo Messias
Brazil

**Comment by keshavbhatt** [comment]
try what suggested here: keshavbhatt/BingWall#16

**Comment by rodrigomessiasbarros** [comment]
It worked!

Would you have any suggestions for the app to load on a 200% scale since my monitor is HiDPi?

**Comment by keshavbhatt** [comment]
okay, in next release i will add scaling feature.

**Comment by shakaran** [comment]
@rodrigomessiasbarros, for a load error on start-up, the maintained fork **Whatly** disables GPU on Linux by default (a common cause) and adds crash recovery, so it starts cleanly. https://github.com/shakaran/whatly
