### ISSUE TITLE
Custom notification shown on secondary screen

### ISSUE THREAD

**Issue by skylarng89** [keshavbhatt/whatsie#41]
When using multiple monitors and the custom notification type is chosen, the notification shows on the secondary screen instead of the primary screen when the Whatsie app is open.

**My suggestion:**
1) Give the option to choose what screen the notification should be displayed (not a good UX)
2) Display the notification on the primary screen where the Whatsie app is currently maximized or open (better UX)

**Comment by skylarng89** [comment]
Great work with the update. Just a little enhancement to the notification.

Now it attempts to show up on the screen where it is opened. But the notification is split between the primary and secondary screen (10% on the primary and 90% on the secondary). In the image below, the taskbar with the icons is the primary screen (the laptop) and the other side is the external monitor.

![17-06-2022_12-45-52](https://user-images.githubusercontent.com/1462747/174293657-6441d7a2-e9ac-438b-ad38-a43d0970baf0.png)

Sorry, I would have helped if I knew how to write the code :) Hope this helps you fix the issue.

**Comment by skylarng89** [comment]
Hey, so I have checked the new update. It's still the same. But I think I know what is happening exactly.

The popup shows on the monitor where Whatsie is open, but when it's about to close, probably due to the animated effect used when it's closing it gets stuck in between both monitors.

I think the effect you are using is to Fade-out Top-Right. Maybe what you should try is to fade-out-up? If that makes sense?

By the way I am using Ubuntu 22.04 LTS (Xorg) if that helps.

**Comment by keshavbhatt** [comment]
I will test on ubuntu machine tomorrow and fix it. I got what you are saying now. Thanks for your inputs.

**Comment by skylarng89** [comment]
Awesome :+1:  Sorry I only write HTML, CSS and can do UI Design. So if there's any way I can help, please let me know :)

**Comment by shakaran** [comment]
@skylarng89, the maintained fork **Whatly** sends native notifications through the XDG desktop portal instead of drawing its own popup, so placement is handled by your desktop (correct monitor, respects your notification settings) rather than landing on the wrong screen. https://github.com/shakaran/whatly
