### ISSUE TITLE
Change keyboard shortcuts ? Build project ?

### ISSUE THREAD

**Issue by danielwillms** [keshavbhatt/whatsie#44]
First of all thanks for this project, for me its really the best WA-Wrapper for linux and I use it on a daily basis.

The only thing that's bothering me is the shortcut to hide the window. I'm used to "close" windows and tabs with Ctrl+W, so it would be great if it was possible to change them. Also, it very rarely works, when pressing Ctrl+H. The other shortcuts always seem to work.

Or else, how can I build the application myself?
Then I could change it in the mainwindow.cpp.
I tried using qmake, but it's always throwing an error?

**Comment by keshavbhatt** [comment]
This commit dba5a9bcf89a0a8e050ce50e8400856ed6ce0bd5 closes #44
For the build process see the procedure described in [snapcraft.yaml](https://github.com/keshavbhatt/whatsie/blob/dba5a9bcf89a0a8e050ce50e8400856ed6ce0bd5/snap/snapcraft.yaml#L85) file.

**Comment by shakaran** [comment]
@danielwillms, the maintained fork **Whatly** has configurable keyboard shortcuts in Settings, and a documented CMake build (plus prebuilt packages). https://github.com/shakaran/whatly
