### ISSUE TITLE
On maximized window, useful content doesn't expand on full viewport

### ISSUE THREAD

**Issue by M0Rf30** [keshavbhatt/whatsie#46]
To have a better idea of what this issue means I put a screenshot (I only capture the top part of the app useful content, for privacy concerns)

![image](https://user-images.githubusercontent.com/491117/174409564-f99f18ae-ffd5-4b16-9aba-13d81bf58f7a.png)

Instead when not maximized there's no padding on both margins (the black areas on the sides), displaying it correctly

![image](https://user-images.githubusercontent.com/491117/174409675-53da223c-40d8-4925-b943-c71ecd7720f6.png)

**Comment by keshavbhatt** [comment]
You will find an option in the settings window now, which will let you toggle the full view mode. The settings is set to use the full view mode by default.
![wrri66OZdh](https://user-images.githubusercontent.com/5965031/175343380-1a17ef0b-f039-406d-838e-c786cad72f71.gif)

**Comment by shakaran** [comment]
The maintained fork **Whatly** lets you scale the page (zoom and interface scale) and collapse the chat list, so the conversation uses the maximized width. https://github.com/shakaran/whatly
