### ISSUE TITLE
git discovering should be disabled in a release

### ISSUE THREAD

**Issue by asarubbo** [keshavbhatt/whatsie#49]
If I get the tarball and try to build, I see:

```
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set). 
```

Obviously it does not work because the tarball does not contain the git history. It should be disabled in case of build from the tarball.

**Comment by M0Rf30** [comment]
It's a warning, not an error. I manage to build it also after these messages.
it successfully generates
```
Info: creating stash file /home/user/whatsie-4.4/.qmake.stash
```
and the `Makefile`
