### ISSUE TITLE
Open other notifications make whatsie active too

### ISSUE THREAD

**Issue by CrazySky2121** [keshavbhatt/whatsie#5]
If I click to any others notifications whatsie opened too.

Ubuntu 20.10
WhatSie snap 0+git.15de59c

**Comment by keshavbhatt** [comment]
Other notifications, mean notifications from other applications ? :flushed:

**Comment by CrazySky2121** [comment]
yep

**Comment by keshavbhatt** [comment]
What desktop environment, OS you using? Can you share screen recording of what is happening?

**Comment by CrazySky2121** [comment]
Ubuntu 20.10 Gnome

I have problems with screen recording because it's affecting personal data..

**Comment by shakaran** [comment]
For clicking an unrelated notification pulling Whatsie to the front, the maintained fork **Whatly** reworked notification and tray activation so only the app's own notifications raise its window. https://github.com/shakaran/whatly

cc @CrazySky2121 @Giako
