### ISSUE TITLE
High cpu usage

### ISSUE THREAD

**Issue by hshaterian** [keshavbhatt/whatsie#51]
After open Whatsie, you'll be faced with high (about 30% of) cpu usage,
I faced it on snap version in linux (ubuntu 22.04)

**Comment by keshavbhatt** [comment]
This is normal, The app is starting at that time :)
In few seconds it goes back to 0-1%

**Comment by hshaterian** [comment]
Yes, It's higher at starting but unfortunately it remains at about 30% cpu usage.
This is for about 5 minutes after start the app ...
![image](https://user-images.githubusercontent.com/1263964/175760857-7898913d-66b6-4ce5-b062-6112f64b095e.png)

**Comment by keshavbhatt** [comment]
> After remove whatsie & reinstall, problem solved ...

Interesting, Could you please watch this behaviour once more and report if it occurs again? I have a few tests that I'd want to run to address this problem.

thank you for bringing this to my attention.

**Comment by hshaterian** [comment]
Hi, from that time I reinstall whatsie It happend again, cpu usage is about 30%.
This time name of process is: snap-exec
![Screenshot from 2022-07-24 17-00-33](https://user-images.githubusercontent.com/1263964/180647170-4594e18a-aeb2-4220-aced-fea9c0880b52.png)

**Comment by hshaterian** [comment]
@keshavbhatt Pleas tell me if I should test anything ...

**Comment by keshavbhatt** [comment]
Hi, yes can you clear app data from with the application settings and restart application and confirm if the CPU usage remain same?

**Comment by keshavbhatt** [comment]
> Hi, from that time I reinstall whatsie It happend again, cpu usage is about 30%.
> This time name of process is: snap-exec
> ![Screenshot from 2022-07-24 17-00-33](https://user-images.githubusercontent.com/1263964/180647170-4594e18a-aeb2-4220-aced-fea9c0880b52.png)
> 
> 

snap-exec is fine its the entry point which start whatsie. Its actually whatsie which is called from a wrapper.

**Comment by hshaterian** [comment]
Should there be 'clear the app data' option in the menu?
I did not find that ...
![image](https://user-images.githubusercontent.com/1263964/180728309-c84e833e-1672-4e09-86b3-58350a3a7f83.png)

And yes, after while process name is whatsie with this cpu usage:
![Screenshot from 2022-07-25 12-22-22](https://user-images.githubusercontent.com/1263964/180729059-c5d1c07e-d828-4e4b-8c38-5e6b7cc63449.png)

**Comment by keshavbhatt** [comment]
Open the app setting window. There are options at bottom. Access setting menu item from system tray icon's context menu. Or use shortcut Ctrl+p

**Comment by hshaterian** [comment]
Yes, I forgot where is the settings ...
first clear: cache ... does not work
then clear: persistent data ... login again and ...
It works & now cpu usage is normal
![image](https://user-images.githubusercontent.com/1263964/180860811-32bcb0c2-6027-4141-b191-dc70b2812292.png)
-----
I faced more problems (more than high cpu usage) recently,
like: not updating messages, not delivering messages or files & so on.

**Comment by shakaran** [comment]
Hi @hshaterian — for anyone still on a Whatsie-style client, the maintained MIT fork **Whatly** exposes the rendering knobs that usually drive high CPU: Settings → Performance lets you turn off GPU compositing, pick a lighter process model (process-per-site), and cap resources. On Linux the GPU is off by default (the usual driver-related culprit). Repo: https://github.com/shakaran/whatly
