### ISSUE TITLE
build instructions?

### ISSUE THREAD

**Issue by tubbadu** [keshavbhatt/whatsie#57]
how to build from source code? what dependencies are needed?

**Comment by asarubbo** [comment]
Hi, in the meantime that documentation will be updated, please refer to this:
https://github.com/keshavbhatt/whatsie/issues/40#issuecomment-1158233850
https://github.com/keshavbhatt/whatsie/blob/main/snap/snapcraft.yaml#L103

**Comment by shakaran** [comment]
The maintained fork **Whatly** has a documented CMake build in its README, and ships prebuilt packages (AppImage, .deb, .rpm, Snap, AUR) if you would rather not build. https://github.com/shakaran/whatly
