### ISSUE TITLE
Missing indicator in Ubuntu Mate

### ISSUE THREAD

**Issue by LyzardKing** [keshavbhatt/whatsie#6]
Hi! Thank you for developing this program.
The only issue I'm having is the fact that the appindicator icon is missing on Ubuntu Mate.
The fix I used in other qt5 snaps is to add this line to the environment part of the yaml:
`XDG_CURRENT_DESKTOP: $XDG_CURRENT_DESKTOP:Unity:Unity7`
This tells the system explicitly to use the appindicator/ayatana icon (which the normal one it should be using anyway).

**Comment by keshavbhatt** [comment]
I don't know how this will impact other desktop environments like KDE XFCE gnome, can you confirm setting the env var won't break my app on other DE?

**Comment by simonv74** [comment]
Hi, same here for me using Elementary OS 5.1.7

**Comment by LyzardKing** [comment]
@keshavbhatt I don't think this should cause issues with other distros.

**Comment by keshavbhatt** [comment]
I have added the [suggested changes](https://github.com/keshavbhatt/whatsie/issues/6#issue-913559619) in latest build recipe [with this commit](https://github.com/keshavbhatt/whatsie/commit/e03ea12c125464fd4b14d417deafc94e49705725)

New updated snap can be tested with `snap refresh whatsie --edge` Please provide feedbacks.

**Comment by keshavbhatt** [comment]
I have tested the latest revision x40 (--edge) on Unity 7 desktop Ubuntu 16.04, Everything works fine.

Please test and confirm if this fixed the tray indicator icon issue for your desktop Environment.

As we will have more tests passed I will publish the update in stable channel.

**Comment by LyzardKing** [comment]
@keshavbhatt It works on my system!
Thanks for looking into it

**Comment by keshavbhatt** [comment]
Promoting to stable channel.

**Comment by shakaran** [comment]
For a missing tray indicator (Ubuntu MATE and other AppIndicator/SNI panels): the maintained fork **Whatly** ships a tray icon that also reflects unread count and connection state, and can be forced monochrome to match the panel. https://github.com/shakaran/whatly

cc @LyzardKing @simonv74
