### ISSUE TITLE
versions mismatch

### ISSUE THREAD

**Issue by asarubbo** [keshavbhatt/whatsie#60]
Hi,

running the 4.7.1 from a tarball reports to be 4.4 because of https://github.com/keshavbhatt/whatsie/blob/e0d15c2ee0589f49cfef293606d69872d16b60f0/src/WhatsApp.pro#L51 and also version.txt reports to be 4.7.0:
https://github.com/keshavbhatt/whatsie/blob/9f566869d49578b12e445f8c275e7f8067daf5be/VERSION.txt

I gues that version(s) should be changed before the tag happens.

**Comment by keshavbhatt** [comment]
They will be aligned from now on. I have created a Release dry run action which will let me know the upcoming version based on semantic versioning convention. I have to run it to know the upcoming version and make update to project file to have the new version updated brefore drafting a new release.
