### ISSUE TITLE
Theme switching

### ISSUE THREAD

**Issue by NovaLibertas** [keshavbhatt/whatsie#62]
Hi! WhatSie does not remember which theme I've selected. I have to config it every time I boot.

Fedora Linux 36 (Workstation Edition)
GNOME 42, Wayland
Kernel: 5.18.9-200.fc36.x86_64

**Comment by keshavbhatt** [comment]
Strange, make sure you have set the theme in whatsapp web settings to system default in this way whatsie will manage theme switching for you. Also, look in settings if you have auto theme switching turned on. If you don't want auto theme switching based on the day and night time you set, turn it off.

**Comment by shakaran** [comment]
@NovaLibertas, the maintained fork **Whatly** has light/dark themes that can follow the system, plus chat themes, switchable from Settings and a shortcut. https://github.com/shakaran/whatly
