### ISSUE TITLE
Lock-screen is triggered also during normal app usage (scroling a chat for example)

### ISSUE THREAD

**Issue by M0Rf30** [keshavbhatt/whatsie#67]
I have a very short time for lockscreen enablement and I noticed that lock is triggered also during the normal and continous usage of the app

**Comment by keshavbhatt** [comment]
Fixed in baa52666b7a69d3b6835675918812502a4049b2b
Thanks for reporting.

**Comment by shakaran** [comment]
The maintained fork **Whatly** has a configurable app lock (set the auto-lock timeout, or lock only when the window hides), so it does not lock while you are using it. https://github.com/shakaran/whatly
