### ISSUE TITLE
INFO snap "whatsie" has bad plugs or slots: audio-playback (unknown interface "audio-playback"); audio-record (unknown interface "audio-record")

### ISSUE THREAD

**Issue by eduardomozart** [keshavbhatt/whatsie#68]
Hello,
When I install whatsie at Deepin 20.6 (based on Debian 10), I'm receiving the following INFO message:

```
2022-08-01T21:07:38-03:00 INFO snap "whatsie" has bad plugs or slots: audio-playback (unknown interface
"audio-playback"); audio-record (unknown interface "audio-record")
``` 

When I try to run it through Deepin Launcher (Start Menu), it doesn't open. When I run it through the ``snap run whatsie`` command, I receive the following error output:

```
022/08/01 21:11:50.360925 cmd_run.go:871: WARNING: cannot create user data directory: failed to verify SELinux context of /home/Eduardo/snap: exec: "matchpathcon": executable file not found in $PATH
error: error running snapctl: Unknown command `is-connected'. Please specify one command of: get, restart, services, set, start or stop
ERROR: snap whatsie is not connected to the qt515-core20 content interface.

Run these commands to make sure required content interface is installed & connected:


snap install qt515-core20

snap connect whatsie:qt515-core20 qt515-core20


```

The ``qt515-core20`` is already installed and connected to whatsie. The ``matchpathcon`` message I could fix it by installing the ``selinux-utils`` package, but the issue persists:

```
2022/08/01 21:15:13.725030 cmd_run.go:871: WARNING: cannot create user data directory: failed to verify SELinux context of /home/Eduardo/snap: exit status 1
error: error running snapctl: Unknown command `is-connected'. Please specify one command of: get, restart, services, set, start or stop
ERROR: snap whatsie is not connected to the qt515-core20 content interface.

Run these commands to make sure required content interface is installed & connected:


snap install qt515-core20

snap connect whatsie:qt515-core20 qt515-core20


```

**Comment by keshavbhatt** [comment]
This is very strange, Please open a forum post if you face this issue with other snaps too. Let me know if its just with Whatsie.
I will also suggest a fresh install of:
- remove with purge: `snap remove --purge whatsie`
- fresh install:  `snap install whatsie`

**Comment by shakaran** [comment]
@eduardomozart, the maintained fork **Whatly** ships native packages (AppImage, .deb, .rpm, AUR) that avoid the snap plug/slot issues, alongside a maintained snap. https://github.com/shakaran/whatly
