### ISSUE TITLE
Blurry status icon 

### ISSUE THREAD

**Issue by simonsaysthis** [keshavbhatt/whatsie#69]
Hello. Thanks for your constant improvement on this app. It would be great if Whatsie could use a dynamic icon for the systray. With 200% scaling on both GNOME and Cinnamon the icon is blurry. See picture

![Screenshot from 2022-08-07 13-41-47](https://user-images.githubusercontent.com/23367458/183288851-ef4c141d-6245-4502-a676-c6ad4d6c4c50.png)

**Comment by keshavbhatt** [comment]
Thanks for reporting this. I will test and provide fix for it in coming days.

**Comment by keshavbhatt** [comment]
Hi, can you confirm that the problem is fixed now with latest Whatsie? I am using 64px icon in system tray. It also support notification counter now.

**Comment by keshavbhatt** [comment]
Assuming it is fixed, hence closing it. Feel free to re-open if issue is still there.

**Comment by simonsaysthis** [comment]
Hi @keshavbhatt thank you so much for fixing this. This is my favourite WA client but I haven't been using it in a while due to the logout bug which is affecting me badly.

**Comment by keshavbhatt** [comment]
I will work on the logout issue this weekend. I hope you will be back once it is fixed :)

**Comment by simonsaysthis** [comment]
Awesome. Of course I will!

**Comment by shakaran** [comment]
@simonsaysthis, the maintained fork **Whatly** redraws the tray icon crisply (composed at full size), reflects the unread count and connection state, and offers a monochrome option. https://github.com/shakaran/whatly
