### ISSUE TITLE
accentuation is not working

### ISSUE THREAD

**Issue by alansenairj** [keshavbhatt/whatsie#7]
It is not accepting accentuation like "ã ô ó" etc. 

Using Ubuntu21.04 pt-br

**Comment by keshavbhatt** [comment]
What do you mean by not accepting? I am able to Paste these characters and send them. 

![Screenshot from 2021-06-09 20-41-14](https://user-images.githubusercontent.com/5965031/121381130-123f0f80-c963-11eb-83fc-6f8878c8a891.png)

**Comment by alansenairj** [comment]
It is not working:
![image](https://user-images.githubusercontent.com/20565821/121382119-ab970300-c91c-11eb-9463-dacfe5ca2ce1.png)

chrome: 
![image](https://user-images.githubusercontent.com/20565821/121382382-edc04480-c91c-11eb-9d72-1c41245e84c1.png)

**Comment by alansenairj** [comment]
that's my configs here: 
![image](https://user-images.githubusercontent.com/20565821/121382911-6e7f4080-c91d-11eb-9201-385a8413f0c7.png)

**Comment by keshavbhatt** [comment]
Hi, I don't have those characters on my keyboard but I tried typing them with virtual keyboard app (onboard) it works perfectly fine here.

**Comment by keshavbhatt** [comment]
> that's my configs here:
> ![image](https://user-images.githubusercontent.com/20565821/121383063-8b1b7880-c91d-11eb-9cbb-4c14f6fa79f5.png)

There is nothing in the settings that will prevent users from typing characters in text input.

**Comment by keshavbhatt** [comment]
Can you post the output of Whatsie when you start it from terminal ?
Open terminal type `whatsie` hit enter to open app.

Copy the whole output from terminal to next comment here.

**Comment by alansenairj** [comment]
of course, here is the output: 

![image](https://user-images.githubusercontent.com/20565821/121425017-57a21380-c948-11eb-8884-df48623ae5da.png)

**Comment by alansenairj** [comment]
I have no idea how to solve this. Could you help me? I'm using  this gnome fonts here: 
![image](https://user-images.githubusercontent.com/20565821/121425847-3e4d9700-c949-11eb-9dba-38ed968c651d.png)

**Comment by keshavbhatt** [comment]
Can you change the system font to Ubuntu and try typing again?

**Comment by alansenairj** [comment]
I swaped to original fonts but I think it was some king of problem of "WhatsApp standalone core" in my system. Web whatsapp is ok via Chrome. I've been installing other Whatsapp apps for Linux and got same problem again. If I use Telegram app here dead keys are working perfectly.

**Comment by keshavbhatt** [comment]
I will look into it.

**Comment by jakley** [comment]
I'm Brazilian, I had the same problem with accents.
So I downloaded the source code, installed qtcreator, loaded the code and compiled it, without making any changes to the code. The new executable allowed the use of accents.
I have no experience with Qt, but if I can help with any information, just let me know.

**Comment by keshavbhatt** [comment]
The problem is i am not able to reproduce this issue on my system as well. I tried typing those characters with virtual soft keyboard and everything just worked fine. I have to test on other machines.

**Comment by alansenairj** [comment]
> tcreator, loaded the code and comp

opa, tudo bem jakley, me passa a dica de como eu faço isso por favor?

**Comment by jakley** [comment]
> > tcreator, loaded the code and comp
> 
> opa, tudo bem jakley, me passa a dica de como eu faço isso por favor?

Massa, "brazuca" na área hehhehe.

Então, eu uso ubuntu 20.04. Fui no site da Qt (https://www.qt.io) e baixei o binário do instalador on-line da versão open source.

No instalador eu escolhi a versão 5.15, vou logo avisando que instalou ~10Gb de arquivos.

Baixei e descompactei o .zip a brach main do código fonte do whatsie

Usando o QtCreator abri o projeto do whatsie

Escolhi o kit Desktop e a Build Profile 

Compilei a build que gerou um executável do whatsie inclusive um atalho .desktop 

Então foi só rodar o executável e seguir os procedimentos para vincular a conta 


English version:
Massa, 'brazuca' in the area hehhehe.

So, I use ubuntu 20.04. I went to the Qt website (https://www.qt.io) and downloaded the online installer binary of the open source version.

In the installer I chose version 5.15, I'll tell you that it installed ~10Gb of files.

I downloaded and unzipped the .zip a brach main from the whatsie source code

Using QtCreator I opened the whatsie project

I chose the Desktop kit and the Build Profile

I compiled the build that generated a whatsie executable including a .desktop shortcut

So just run the executable and follow the procedures to link the account

**Comment by jakley** [comment]
Eu só preciso saber como manter o whatsie funcionando sem precisar manter os 10Gb de arquivos do Qt.

@keshavbhatt você poderia me dar uma ajuda com isso? 

Quando desinstalei o Qt fiz uma cópia das bibliotecas e tentei usar de forma manual, tentei em várias pastas, inclusive na pasta do projeto, mas sem sucesso.

Não queria ter que manter os 10Gb. Eu programo só em python, e só por hobby.

English version:
I just need to know how to keep whatsie running without having to keep the 10Gb of Qt files.

@keshavbhatt could you help me with this?

When I uninstalled Qt I made a copy of the libraries and tried to use them manually, I tried in several folders, including the project folder, but without success.

I didn't want to have to keep the 10Gb. I only program in python, and just as a hobby.

**Comment by jakley** [comment]
> The problem is i am not able to reproduce this issue on my system as well. I tried typing those characters with virtual soft keyboard and everything just worked fine. I have to test on other machines.

When I compiled the project I didn't need to make changes, I just compiled

I had no crashes and no error messages.

It compiled , and when I ran the program it started to accept accents

Portuguese version: 

Quando eu compilei o projeto não precisei fazer alterações, apenas compilei

Não tive falhas e nem mensagens de erro.

Compilou de primeira, e quando executei o programa ele já passou a aceitar acentos

**Comment by keshavbhatt** [comment]
I will make an appimage for whatsie, and announce it here. You can use that to prevent the qt install. Also Qt do not take 10Gb, you should open the maintenance tool and remove unnecessary components.

**Comment by ibere82** [comment]
I am also Brazilian and I have the same problem. I want to try doing the walkthrough suggested by @jakley. Thanks @jakley. But 10 GB is too much. However, I want to expose the details about this problem to try to solve it. In Brazil, for example, to type the character 'é' (\u00E9), we first press the acute accent key, then we press the 'e ' key.

But, note that when we press the acute accent key, it doesn't show anything on the screen, but this event is captured and processed to change the result when we press the "e" key.

This is the behavior when using the physical keyboard, as the physical keyboard does not have a key to char 'é' (\u00E9). Thus, the combination of both keyboards events results in this unicode char.
This is a behavior of a Latin keyboard Layout configuration. However, when you use a virtual keyboard, the behavior is different, probably because this keyboard must have a specific key for this unicode.

The issue with your app is not a screen output problem. If I type in another text editor, copy and paste into your whatsie, nothing goes wrong. Text with Latin characters is successfully pasted.

But, the problem happens when we type directly into your app. When I press the acute accent key and then the 'e' key, the result on the screen is the 'e' character and not the 'é' which is the expected behavior. This is likely a keyboard layout configuration error. 

I think that the tests routines should dispatch the specific keyboards events to test the correctly latin layout keyboard configuration.

Thank for your attention.

**Comment by keshavbhatt** [comment]
wait for the appimage.

**Comment by RoinujNosde** [comment]
https://bugs.launchpad.net/snapd/+bug/1936962
I've reported this bug on launchpad, it should help if you guys marked it as "This bug affects me".

**Comment by RoinujNosde** [comment]
@keshavbhatt unfortunately my issue was closed as invalid, they said the bug is due to how the app was built and you could discuss this on their forums.

**Comment by keshavbhatt** [comment]
I will open a forum post as suggested.

**Comment by RoinujNosde** [comment]
Post the link to the discussion when you open it, please.
I would like to follow it.

**Comment by alansenairj** [comment]
Hi guys. I solved my problem here. It was a IBUS problem. I put it on IBUS mode here in Ubuntu 21.04: 

![Captura de tela de 2021-09-10 11-14-45](https://user-images.githubusercontent.com/20565821/132867788-6b762a70-61f9-4123-851e-918f58ca3957.png)


Now everything is working very well. I hope you guys can solve it too.

**Comment by voltaxvoltax** [comment]
> Hi guys. I solved my problem here. It was a IBUS problem. I put it on IBUS mode here in Ubuntu 21.04:
> 
> ![Captura de tela de 2021-09-10 11-14-45](https://user-images.githubusercontent.com/20565821/132867788-6b762a70-61f9-4123-851e-918f58ca3957.png)
> 
> Now everything is working very well. I hope you guys can solve it too.

I've tried this on Ubuntu 20.04, and it doesn't work, still no accents for Portuguese chars ( á,à,ó,é,ã)
It only works if we copy-paste.
Can you please fix this issue?

**Comment by keshavbhatt** [comment]
Hi can any one you try, whatsie from edge channel and let me know if the problem is still there?

snap refresh whatsie --edge

**Comment by RoinujNosde** [comment]
> snap refresh whatsie --edge

Didn't fix it.

**Comment by keshavbhatt** [comment]
Thanks for the update. I am still trying to figure out a solution :(

**Comment by keshavbhatt** [comment]
Hi @RoinujNosde can you try running : `LANG="en_IN.UTF-8" whatsie`

**Comment by keshavbhatt** [comment]
The issue is fixed in 0483b030043f13fe048f575882ffb78d4177b479
You can refresh whatsie with `snap refresh whatsie --stable` to get the changes.
Feel free to reopen for further assistance.

**Comment by manozzo** [comment]
hello.
I made the refresh command, but the portuguese accents doesn't work yet =/
I just need do this command? `snap refresh whatsie --stable` ?

**Comment by keshavbhatt** [comment]
> I just need do this command? `snap refresh whatsie --stable` ?

Yeah that is sufficient, you can also run `rm -rf ~/snap/whatsie` to remove the old configurations of whatsie.

**Comment by voltaxvoltax** [comment]
Updated to version 2, but the problem remains.

**Comment by RoinujNosde** [comment]
It's working here, thanks!

**Comment by joaorodrigo** [comment]
This bug is closed, but the problem persists, any update?

**Comment by Leolucas12** [comment]
Same thing here, using Xubuntu 22.04. If I try to change the language to pt-BR, restart the computer and open Whatsie, the accents work. But if the system language is en-US, the language I use, accents don't work. Tried to change the language in the Whatsie settings, but it doesn't seem to work.

**Comment by gtonussi** [comment]
Hi, just reporting that the issue remains, using latest version from snap and Ubuntu 22. I am also using my system in english. When I type "é ã" for example it just goes by "e a". It would be amazing if I could remain using the system in english..

**Comment by GoulartNogueira** [comment]
It might be related to Telegram's bug.
It looks like they solved it:

https://github.com/telegramdesktop/tdesktop/issues/1041

**Comment by davincif** [comment]
I'm having the same problem. And notice that if I copy/past a "á", for instance, from another place to there, it works. But if I type it, it doesn't.

**Comment by Canudin** [comment]
```
>snap refresh whatsie --stable
snap "whatsie" has no updates available
>rm -rf ~/snap/whatsie
>LANG="en_IN.UTF-8" whatsie
Qt: Session management error: Could not open network socket
WhatSie is already running with PID: 24398 by USER: gzmarcatto
>snap refresh whatsie --edge
whatsie (edge) v4.10.3.74216cf from keshavbhatt (keshavnrj✪) refreshed
```
Tried everything above, still not being able to use accentuation.

> I'm having the same problem. And notice that if I copy/past a "á", for instance, from another place to there, it works. But if I type it, it doesn't.

And the behavior is the same for me, copy/paste works, but typing doesn't

**Comment by thiagorsti** [comment]
Same problem here. Using 4.10 version from edge channel. Any solution?

**Comment by lbdonato** [comment]
Same problem, Ubuntu 22.04, IBUS, my installation in english.

**Comment by fscosta** [comment]
I get this error when I run from the command line:

`xkbcommon: ERROR: /snap/whatsie/142/qt515-core20/usr/share/X11/locale/pt_BR.UTF-8/Compose:54:9: failed to open included Compose file "/usr/share/X11/locale/en_US.UTF-8/Compose": No such file or directory
xkbcommon: ERROR: /snap/whatsie/142/qt515-core20/usr/share/X11/locale/pt_BR.UTF-8/Compose:54:9: failed to parse file
qt.xkb.compose: failed to create compose table
`

What is wierd is that the file is right there:

`-rw-r--r-- 1 root root 531904 abr  3  2022 /usr/share/X11/locale/en_US.UTF-8/Compose`

Shouldn't it be looking for the pt_BR file instead of en_US?

**Comment by fscosta** [comment]
And the directory 'qt515-core20' does not exist, btw, in '/snap/whatsie/142/qt515-core20/usr/share/X11/locale/pt_BR.UTF-8/Compose'

**Comment by KrauzerPH94** [comment]
I'm facing the same issue, been using WhatsDesk instaed, it works fine with the accets

**Comment by Mateus5187** [comment]
Galera se vocês estiverem com o sistema em inglês capaz do whatsie não reconhecer o acentos. tentem colocar o linux em português. Aqui estava enfrentando o mesmo problema. vão em idioma e região > gerenciar idiomas instalados - Alterem para português e reiniciem a maquina.
![Captura de tela de 2023-07-28 00-24-33](https://github.com/keshavbhatt/whatsie/assets/39628128/f626fc22-0e85-4760-9d47-aff8e92c574f)
![Captura de tela de 2023-07-28 00-24-51](https://github.com/keshavbhatt/whatsie/assets/39628128/9b1665ef-08da-4bb2-9a1a-7c6baab73d0d)

**Comment by hpicelli** [comment]
Mateus5187, o grande problema é usar o sistema em ptbr. (the big deal is to use the system in pt-br).

**Comment by JPachiari** [comment]
Pessoal, também sou brasileira e estava com o mesmo problema. 

Seguem informações do OS  que está instalado, mesmo com o idioma em inglês do sistema:

![image](https://github.com/keshavbhatt/whatsie/assets/145880893/993f045f-c369-4dc9-98ba-df6ed91422c6)

Aqui deu certo, assim:

- Fiz a remoção do WhatSie via terminal (o meu era snap), com o comando:

`sudo snap remove whatsie`
 
- Reinstalei via Flatpak, com o comando: 

`flatpak install flathub com.ktechpit.whatsie`

Testei e deu certo:

![image](https://github.com/keshavbhatt/whatsie/assets/145880893/a2fb0947-8e7a-489e-b373-e4427517bd6c)

Se precisar instalar e configurar o Flatpak: [https://flathub.org/pt-BR/setup/Ubuntu](https://flathub.org/pt-BR/setup/Ubuntu)

Espero que funcione para vocês.

**Comment by hpicelli** [comment]
Hello! Mine here are Flatpak and the error persists.
Ola! O meu está instalado via Flatpak e o erro persiste.

Best regards.
Atenciosamente.

Henrique

**Comment by magau** [comment]
> Pessoal, também sou brasileira e estava com o mesmo problema.
> 
> Se precisar instalar e configurar o Flatpak: https://flathub.org/pt-BR/setup/Ubuntu
> 
> Espero que funcione para vocês.

I was also having the same issue, and solved it with [JPacB](https://github.com/JPacB) proposed workaround, by using _flatpak_ installation method.

Thanks for the advice, JPacB!
It was really getting annoying...

**Comment by shakaran** [comment]
@alansenairj — for anyone whose accents / dead keys never worked here: that was largely a Qt5 WebEngine input-method bug. The maintained fork **Whatly** is built on current Qt6 WebEngine, where dead-key/IME accent input behaves much better. If this bit you on the old build, it's worth retrying. https://github.com/shakaran/whatly
