### ISSUE TITLE
qmake error >> Project ERROR: Could not find feature webengine-spellchecker.

### ISSUE THREAD

**Issue by Hyphaed** [keshavbhatt/whatsie#70]
When typing qmake in terminal it shows me this error >>

Project ERROR: Could not find feature webengine-spellchecker.

**Comment by keshavbhatt** [comment]
If you are ubuntu make sure you have `qtwebengine5-dev-tools` package installed.

**Comment by keshavbhatt** [comment]
What distribution you are using and how you installed Qt on it? Also provide the version of distribution along with installed Qt version.

The problem seems to be missing executable that is required to compile the dictionaries and convert them to be consumed by qtwebengine.

**Comment by Hyphaed** [comment]
I'm on PopOS 22.04

I was using latest QT from their webpage

I've just uninstalled it yesterday, I do not want to have packages on my system I do not use

**Comment by keshavbhatt** [comment]
Can you provide the output of `dpgk -L qtwebengine5-dev-tools`

**Comment by Hyphaed** [comment]
Command 'dpgk' not found, did you mean:
  command 'dpkg' from deb dpkg (1.21.1ubuntu2.1)

**Comment by keshavbhatt** [comment]
Sorry dpkg not dpgk

**Comment by Hyphaed** [comment]
/.
/usr
/usr/lib
/usr/lib/qt5
/usr/lib/qt5/bin
/usr/lib/qt5/bin/qwebengine_convert_dict
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/qt5
/usr/lib/x86_64-linux-gnu/qt5/bin
/usr/share
/usr/share/doc
/usr/share/doc/qtwebengine5-dev-tools
/usr/share/doc/qtwebengine5-dev-tools/changelog.Debian.gz
/usr/share/doc/qtwebengine5-dev-tools/copyright
/usr/lib/x86_64-linux-gnu/qt5/bin/qwebengine_convert_dict

**Comment by keshavbhatt** [comment]
Looking at the content it seems the tool is installed properly, why your qmake was not finding it another issues, you need to stick with one install of qt.

You require to setup your Qt sdk properly, either use the one that comes with distribution or use what Qt site provide. Please find some resources on internet about that how to install and make qt ready for development.

I recommend using what your distribution provide so set up Qt properly and configure the kit properly to build the source. 

You can use multiple but you need the knowledge to maintain them.

**Comment by shakaran** [comment]
To skip the build pain entirely, the maintained fork **Whatly** moved to CMake and ships prebuilt packages (AppImage, .deb, .rpm, Snap, plus Windows/macOS), with spellcheck dictionaries bundled — no need to fight the qmake spellchecker feature. https://github.com/shakaran/whatly

cc @Hyphaed
