### ISSUE TITLE
CPU usage is high

### ISSUE THREAD

**Issue by yuvalaviel** [keshavbhatt/whatsie#72]
How can I test what it is doing?

WhatSie
Version: 4.8
Source Branch: main
Commit Hash: 2837c87
Build Datetime: 2022-08-27T17:00:53UTC
Qt Runtime Version: 5.15.4
Qt Compiled Version: 5.15.4
System: Ubuntu Core 20
Architecture: x86_64

[lshw.txt](https://github.com/keshavbhatt/whatsie/files/9461496/lshw.txt)

**Comment by keshavbhatt** [comment]
You have to build the code from source and run the app in debug mode, that will enable the remote debugging of webengine on port 9421 you then open the a chromium based browser to see what is going on with the page loading. Open page localhost:9421 to see the the debug console.

**Comment by keshavbhatt** [comment]
We will track this issue here https://github.com/keshavbhatt/whatsie/issues/58

**Comment by shakaran** [comment]
@yuvalaviel, for high CPU, the maintained fork **Whatly** disables GPU acceleration on Linux by default and exposes compositing and process-model switches in Settings > Performance to bring it down. https://github.com/shakaran/whatly
