### ISSUE TITLE
Whatsie closes immediately 

### ISSUE THREAD

**Issue by JulianGibelli** [keshavbhatt/whatsie#73]
The app closes immediately after sending a document via chat

**Comment by keshavbhatt** [comment]
Fixed in 5e50519c75d7110c232f82db580a76b23aba04cd

**Comment by shakaran** [comment]
The maintained fork **Whatly** disables GPU on Linux by default (a common cause of closing on launch) and adds self-healing crash recovery. https://github.com/shakaran/whatly
