### ISSUE TITLE
Support for Flatpak and Appimage

### ISSUE THREAD

**Issue by dtantono** [keshavbhatt/whatsie#77]
Hi
I know whatsie support snap. But, not everyone likes that. Is it possible to support flatpak and appimage?

**Comment by keshavbhatt** [comment]
Flatpak is supported https://flathub.org/apps/details/com.ktechpit.whatsie

**Comment by shakaran** [comment]
@dnet890, the maintained fork **Whatly** ships both a Flatpak and an AppImage (plus .deb, .rpm, Snap and AUR). https://github.com/shakaran/whatly
