### ISSUE TITLE
Dictionary

### ISSUE THREAD

**Issue by Trebor87** [keshavbhatt/whatsie#78]
I've installed Whatsie, using Pacman in Arch, all works well except I have no dictionary. I've chosen select language from the multiple choisis fr_FR

I'm running Arch English setup but need French Dictionary when using Whatsie as all are french ? So what have I missed ?

**Comment by keshavbhatt** [comment]
Can you share the screenshot of your settings window? 
Thanks

**Comment by Trebor87** [comment]
![Whatsie settings](https://user-images.githubusercontent.com/55857416/191823082-c3c88e42-38ea-413a-8122-c8a4c8a3d646.jpg)


Here you go :)

**Comment by shakaran** [comment]
@Trebor87, for spell-check dictionaries, the maintained fork **Whatly** bundles them and offers a language picker in Settings, so spell check works out of the box. https://github.com/shakaran/whatly
