### ISSUE TITLE
Spell checker doesn't work

### ISSUE THREAD

**Issue by anibalgh** [keshavbhatt/whatsie#79]
Hello, I have the language set to Spanish and the spell checker activated but the application does not show me spelling errors or possible corrections.

**Comment by keshavbhatt** [comment]
How you install the application?

**Comment by anibalgh** [comment]
Hi!
`sudo snap install whatsie`

**Comment by anibalgh** [comment]
Mi OS:
```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

**Comment by hZorah** [comment]
Can confirm this also happens in Portuguese.

**Comment by shakaran** [comment]
For a non-working spell checker, the maintained fork **Whatly** bundles the Qt WebEngine spellcheck dictionaries and exposes a language picker in Settings, so it works out of the box without hunting for `.bdic` files. https://github.com/shakaran/whatly

cc @anibalgh @Hellvol @cesar19004
