### ISSUE TITLE
Whatsie stuck on "organizing messages"

### ISSUE THREAD

**Issue by tubbadu** [keshavbhatt/whatsie#80]
it's been a few days that whatsie no longer achieve to connect to my whatsapp account, it gets stuck on "organizing messages" and after a while it disconnects. I tried reconnecting with the QR code but nothing changed.
using whatsapp web on the browser (firefox 104.0.2) works as usual.

I built from source some month ago and it used to work well, it started not to work just a few days ago
I tried rebuilding the latest version but nothing changed, still stuck
I also tried deleting cache and data from settings but still no success

**Comment by keshavbhatt** [comment]
Remove all other sessions from your whatsapp phone, and try again after clearing whatsie app data from setting.

**Comment by shakaran** [comment]
For the stuck "organizing messages" screen, the maintained fork **Whatly** is on current Qt6 WebEngine and lets you clear cached web data in Settings, which usually gets past it. https://github.com/shakaran/whatly
