### ISSUE TITLE
It looks as I was kicked out of some group chats

### ISSUE THREAD

**Issue by andreaemonti** [keshavbhatt/whatsie#84]
There are two whatsapp groups on which I cannot text from whatsie because instead of the usual space where to input text I see the message
_You can't send messages to this group because you're no longer a participant._
but from my phone I still can (I am still in those groups).

System: Manjaro KDE on wayland
Whatsie version: latest on AUR (just installed)

**Comment by keshavbhatt** [comment]
Please try to reload the app or maybe wait for it to load properly. BTW its not whatsie's issue.
