### ISSUE TITLE
Whatsie stuck on "organizing messages"

### ISSUE THREAD

**Issue by JulianGibelli** [keshavbhatt/whatsie#86]
Hi, Im on Ubuntu 22.04 LTS and whatsie gets stuck on organizing messages. Its been malfunctioning for around 4/5 days.
![image](https://user-images.githubusercontent.com/79370118/194913838-a1a324f6-1676-48eb-baae-fce424241c96.png)

**Comment by elvis-doug-jan** [comment]
Same thing here...
Sometimes reinstalling solves the problem, but I notice that it is also consuming ~30% of the CPU constantly. Tested by Snap and Flatpak, both had the same behavior.

**Comment by koenr** [comment]
Same here on Ubuntu 20.04.

Version: 4.10
Source Branch: main
Commit Hash: 74216cf
Build Datetime: 2022-12-18T21:07:56UTC
Qt Runtime Version: 5.15.4
Qt Compiled Version: 5.15.4
System: Ubuntu Core 20
Architecture: x86_64

I get this output when starting command line:
```
Qt: Session management error: Could not open network socket
propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.661\" (uid=1000 pid=63553 comm=\"/snap/whatsie/136/usr/bin/whatsie \" label=\"snap.whatsie.whatsie (enforce)\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=35219 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.661\" (uid=1000 pid=63553 comm=\"/snap/whatsie/136/usr/bin/whatsie \" label=\"snap.whatsie.whatsie (enforce)\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=35219 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
"Object path cannot be empty"
```

**Comment by RabanalGsus** [comment]
Having the same problem here Manjaro KDE 5.26.4 Qt version 5.15.7.
Tried pamac manager and yay, both behaving equally, after sometime working normally it stops working and I can't do nothing, just reinstall and relog in.

**Comment by keshavbhatt** [comment]
Whenever it happens, clear app data from application settings (open with Ctrl+P) and restart the application.
I am working to fix the issue.

**Comment by RabanalGsus** [comment]
Thanks!

**Comment by CRC-Mismatch** [comment]
Duplicate (and confirmation) of #88 [(comment 1308274306)](https://github.com/keshavbhatt/whatsie/issues/88#issuecomment-1308274306)

**Comment by keshavbhatt** [comment]
Please verify this with new version 4.15 of Whatsie released today and re-open the ticket again if the problem still persists.
Thanks

**Comment by shakaran** [comment]
For the stuck "organizing messages" screen, the maintained fork **Whatly** is on current Qt6 WebEngine and lets you clear cached web data in Settings, which usually gets past it. https://github.com/shakaran/whatly

cc @JulianGibelli @CRC-Mismatch @RabanalGsus @elvis-doug-jan @koenr
