### ISSUE TITLE
Whatsie keeps logging out

### ISSUE THREAD

**Issue by bagoviggo** [keshavbhatt/whatsie#87]
After a successful link to the device  the whatsie app keeps logging out

**Comment by keshavbhatt** [comment]
Please clear the appdata from settings and restart the application.
Also if possible, provide what is the frequency of you getting logged out.
Thanks.

**Comment by muloka** [comment]
Whatsie for me after a fresh install and initial linking to my WhatsApp account kept logging me out.

Clearing the appdata from settings and restarting the application, then re-linking to my WhatsApp account worked like a charm. 

Thank you

**Comment by shakaran** [comment]
For getting logged out repeatedly, the maintained fork **Whatly** keeps a persistent per-account profile, so the session survives restarts and stays linked. https://github.com/shakaran/whatly

cc @bagoviggo @muloka
