### ISSUE TITLE
Not sending or receiving messages

### ISSUE THREAD

**Issue by null92** [keshavbhatt/whatsie#88]
Since yesterday, at Ubuntu (22) and Mint (Vanessa), I can't receive or send messages over WhatSie. I already tried reinstall, unsuccessfully.

**Comment by CRC-Mismatch** [comment]
(Ubuntu 22.04 + Nvidia 510.85.02; Snap install) I've been having the same problems and worse. Most often than not, "Render process stopped working", and when not, nothing loads or gets sent)

**Comment by keshavbhatt** [comment]
Seems like the page is failing to load and hanging forever.

Can you try these:
- clear persistant data and restart the application
- `snap remove whatsie --purge` (if previous step didn't worked for you) and `snap install whatsie`

**Comment by null92** [comment]
> Seems like the page is failing to load and hanging forever.
> 
> Can you try these:
> 
>     * clear persistant data and restart the application
> 
>     * `snap remove whatsie --purge` (if previous step didn't worked for you) and `snap install whatsie`

Didn't work =(

**Comment by CRC-Mismatch** [comment]
> Seems like the page is failing to load and hanging forever.
> 
> Can you try these:
> 
>     * clear persistant data and restart the application
> 
>     * `snap remove whatsie --purge` (if previous step didn't worked for you) and `snap install whatsie`

I did both, and it worked fine for one or two days, then started acting up again...

**Comment by CRC-Mismatch** [comment]
Although still unidentified, the error remains consistent... Once again, I have to delete Cache & Persistent Data, lose all my stickers and negotiate keys with every contact I open :confounded:

**Comment by soumyaDghosh** [comment]
Same issue here, whatsie randomly stops showing or sending new messages.

**Comment by winstonma** [comment]
It happens to me too. In **flatpak** version you can clear the cache by

```bash
# FLATPAK remove Whatsie App cache

# Close Whatsie First

# Delete Whatsie App cache
$ rm -rf ~/.var/app/com.ktechpit.whatsie/

# Open Whatsie and Log In again
```

If it doesn't work for you you can 
```bash
# FLATPAK reinstall Whatsie

# Close Whatsie First

# Uninstall Whatsie App and remove app cache
$ flatpak uninstall --delete-data com.ktechpit.whatsie

# Install Whatsie
$ flatpak install flathub com.ktechpit.whatsie

# Open Whatsie and Log In again
```

**Comment by major-mayer** [comment]
I just had the same problem on Manjaro using the WhatSie version from AUR (so no Snap).
I had to delete data completely using the button in the settings.

Is there any way we could help to debug this problem?

**Comment by keshavbhatt** [comment]
Please verify this with new version 4.15 of Whatsie released today and re-open the ticket again if the problem still persists.
Thanks

**Comment by pea-kayzar** [comment]
This is still happening @keshavbhatt.

Installed fresh after 4.15 update with snap, also had the same problem when installed via the ubuntu application store. Ubuntu 22.04.

Works for a while but then becomes out of sync and unusable. The only solution I've found is to re-link which takes some time and isn't worth it for the frequency that this occurs.

![image](https://github.com/keshavbhatt/whatsie/assets/65439061/b46507c5-f83d-4ef2-b972-1c362586d13e)

**Comment by shakaran** [comment]
For messages not sending or receiving, the maintained fork **Whatly** runs on current Qt6 WebEngine tracking today's WhatsApp Web, which restored messaging for many who hit this on the old build. https://github.com/shakaran/whatly

cc @null92 @CRC-Mismatch @major-mayer @pea-kayzar @soumyaDghosh @winstonma
