### ISSUE TITLE
[Feature Request] Add some security measures

### ISSUE THREAD

**Issue by literalEval** [keshavbhatt/whatsie#89]
It would be nice if we implement some sort of locking mechanism like it has fingerprint lock on the android version.

I would love to work on this issue. Do let me know if it sounds exciting to you.

**Comment by keshavbhatt** [comment]
Whatsie already comes with locking feature. Its not super secure but it prevent someone from accessing loggedIn account from being directly accessed by random user. 

To enable the locking, Open settings -> Check App locking checkbox -> set applock password. There are other options to auto lock app after certain interval of time.

**Comment by literalEval** [comment]
Yeah got it :smile: I had tried to find something like this earlier, but couldn't find one. Just realized that those options come with right click on the tray icon.

**Comment by shakaran** [comment]
@literalEval, the maintained fork **Whatly** has a screen-lock feature (lock the app behind a passcode), alongside other privacy options like chat-list blur. https://github.com/shakaran/whatly
