### ISSUE TITLE
Window minimum width is too small

### ISSUE THREAD

**Issue by RoinujNosde** [keshavbhatt/whatsie#9]
![whatsie](https://user-images.githubusercontent.com/6441328/125201755-c542a780-e246-11eb-825e-b6b62e6afbe9.png)

https://github.com/keshavbhatt/whatsie/blob/574acf05baef63237769b6a301b4ed36c21fff70/src/mainwindow.cpp#L27
This could be 700

**Comment by keshavbhatt** [comment]
will investigate. thanks

**Comment by keshavbhatt** [comment]
You can resize to size of your choice and the app will remember your preferences in next app start.

**Comment by keshavbhatt** [comment]
Made it 800px

**Comment by RoinujNosde** [comment]
Thanks!
Could you reduce the minimum height too?
Maybe 300 or 400
It takes too much space in my low resolution monitor

**Comment by keshavbhatt** [comment]
okay
