### ISSUE TITLE
Excessive ram and vram usage

### ISSUE THREAD

**Issue by Terkyz** [keshavbhatt/whatsie#90]
Every time I open and close Whatsie its consumption doubles, reaching a maximum of 700mbs of both VRAM and RAM.

**Comment by major-mayer** [comment]
In my case the RAM usage doesn't double/ increase when I open and close Whatsie, but still for some reason it reached 1.3 GiB which I think is a bit too much, even for a web app.
![grafik](https://github.com/keshavbhatt/whatsie/assets/17907799/7ab203c7-bd3f-46ec-a625-20e6ead805ae)
Anything else that you could use to debug the memory usage? @keshavbhatt

**Comment by shakaran** [comment]
For high RAM and VRAM, the maintained fork **Whatly** disables GPU on Linux by default (cutting VRAM), starts V8 in optimize-for-size mode, and lets you cap the JS heap in Settings > Performance. https://github.com/shakaran/whatly

cc @Terkyz @major-mayer
