### ISSUE TITLE
Missing indicator in flatpak

### ISSUE THREAD

**Issue by LyzardKing** [keshavbhatt/whatsie#91]
Hi,
as noted a while back in #6 
the indicator icon is missing in ubuntu-mate. This time the issue is in the flatpak.
The solution however is the same: add the env variable `XDG_CURRENT_DESKTOP=$XDG_CURRENT_DESKTOP:Unity:Unity7`

I can't really test how it works in other distros/DEs however

**Comment by keshavbhatt** [comment]
Tested latest build on Ubuntu 22.04 it works as expected.

**Comment by shakaran** [comment]
The maintained fork **Whatly** shows a proper tray indicator (unread count and connection state), including in the Flatpak. https://github.com/shakaran/whatly
