### ISSUE TITLE
How scheduler message?

### ISSUE THREAD

**Issue by adibpwd** [keshavbhatt/whatsie#94]
how to send scheduled messages on whatsie, offline is fine, no need for cloud, 100% local

**Comment by keshavbhatt** [comment]
Sorry I dont interfare with Whatsapp web in any way. If this feature is provided by upstream its fine, I have no plans to implement any such feature my self.

**Comment by shakaran** [comment]
@adibpwd, the maintained fork **Whatly** has a built-in Scheduled Messages feature (queue a message to send at a set time), in the tray menu. https://github.com/shakaran/whatly
