### ISSUE TITLE
Are there any plans for a TUI version?

### ISSUE THREAD

**Issue by slarrain** [keshavbhatt/whatsie#95]
I really like `WhatSie`. But it is true that it has competitors in the Linux world. What is truly lacking is a fully featured WhatsApp TUI/CommandLine client.

There used to be https://github.com/normen/whatscli/ but it doesn't work anymore. I am thinking of something like [this](https://github.com/paul-nameless/tg/) but for whatsapp.

And since `WhatSie` already has a rudimentary `cli` functionality, maybe, perhaps, this is something the developer would be interested in?

I don't intend to be ungrateful for this awesome free and open source piece of software. Just trying to poke the developers curiosity.

**Comment by Auri3l** [comment]
aww, whatscli died?

**Comment by keshavbhatt** [comment]
Sorry, No. 
Not right now.
