### ISSUE TITLE
Native notifications

### ISSUE THREAD

**Issue by garageman2335** [keshavbhatt/whatsie#96]
I'm really liking the QT version of whatsapp. However I think it would integrate better with desktop environments if it used native notifications (such as KNotification instead of QtWebEngineNotification)

**Comment by keshavbhatt** [comment]
You can switch the notification type in settings.

**Comment by shakaran** [comment]
@mattsho03, the maintained fork **Whatly** sends native notifications through the XDG desktop portal (works on Wayland and sandboxed setups). https://github.com/shakaran/whatly
