### ISSUE TITLE
Doesn't find other partition on my SSD Drive

### ISSUE THREAD

**Issue by christian179717** [keshavbhatt/whatsie#97]
Hello,

sadly Whatsie doesn't find my other partition on my SSD Drive. I've one for my Data and another one for system and programs. Sadly only the system partition is available and the folder where the partition is mounted isn't found.

System: Mint 21
Installation method: Snap (with other snap programs it works)
Version: 4.10

Debug Info:

Version: 4.10
Source Branch: main
Commit Hash: 74216cf
Build Datetime: 2022-12-18T21:07:56UTC
Qt Runtime Version: 5.15.4
Qt Compiled Version: 5.15.4
System: Ubuntu Core 20
Architecture: x86_64

**Comment by keshavbhatt** [comment]
Please run this command to enable access the removable media if you are connecting the ssd as removable device(USB?).
`snap connect whatsie:removable-media` 

I have to add mount-observe plug in order to see the other mounted devices. expect this in next version. 

Thanks for opening this issue.

**Comment by christian179717** [comment]
Sadly it still does not work.

**Comment by keshavbhatt** [comment]
> Sadly it still does not work.

Please wait for the next release, i will add mount-observe plug to enable support to read from mounted devices.

**Comment by keshavbhatt** [comment]
`mount-observe` was added in https://github.com/keshavbhatt/whatsie/commit/63440d96fba825ea2831b7f7f07730a0c5626fa1

You can turn it on to allow whatsie see your mounted devices.

**Comment by shakaran** [comment]
@christian179717, the maintained fork **Whatly** has a "use native file dialog" option and ships native packages (not the confined snap), so the file picker can reach your whole filesystem. https://github.com/shakaran/whatly

**Comment by christian179717** [comment]
I've switched in the meantime to Manjaro, and I'm bridging my WhatsApp messages to Matrix, so I only need a Matrix client.
