### ISSUE TITLE
Whatsie gets unlinked when marking message as unread

### ISSUE THREAD

**Issue by jazzmess** [keshavbhatt/whatsie#99]
Hi, I'm not 100% positive but I believe this issue happens when talking to a specific contact or marking it unread. Whatsie gets unlinked, so in my device I get the following message:

`"Your devices were logged out due to an unexpected issue. Please relink your devices."`

This is the output of the terminal:
`Gtk-Message: 14:27:50.397: Failed to load module "xapp-gtk3-module"`
`"test1" checkLoadedCorrectly()/loadingQuirk()/doReload() 4`
`"test1" checkLoadedCorrectly()/loadingQuirk()/doReload() 3`

Also, before marking as unread I zoomed out twice, which I would think is irrelevant.

I would like to know how to help, as I don't see any characteristic with this particular contact that triggers this issue (which does not happen when talking to other contacts).

**PC Specs:**
> OS: archcraft rolling
> Kernel: x86_64 Linux 6.1.7-arch1-1
> Shell: zsh 5.9
> Resolution: 1920x1280
> WM: OpenBox
> WM Theme: Arc-Dark
> GTK Theme: Arc-Dark [GTK2/3]
> Icon Theme: Arc-Circle
> Font: Noto Sans 9
> Disk: 18G / 229G (8%)
> CPU: 11th Gen Intel Core i7-1180G7 @ 8x 4.6GHz [63.0°C]
> GPU: Iris Xe Graphics
> RAM: 9417MiB / 15666MiB

**Comment by keshavbhatt** [comment]
Hi @jazzmess I tried to reproduce the reported issue, but no luck. I dont think the relinking request from whatsapp-web has anything to do with whatsie. For some reasons they thought you session need to be revalidated. Also the zooming has nothing to do with relinking. From version 4.12 the Ctrl+mouse_wheel scrolling is diabled on the page. Users are requested to set their zoomlevel in settings(Ctrl+P to open settings).

**Comment by shakaran** [comment]
@jazzmess, the maintained fork **Whatly** runs current Qt6 WebEngine and keeps a persistent session, which avoids this class of unlink issues. https://github.com/shakaran/whatly
